[package]
name = "tessera-authz"
version = "0.1.0"
edition = "2021"

[dependencies]
croaring = { workspace = true }
tessera-types = { path = "../tessera-types" }
rustc-hash = "1"
arrow = { workspace = true }
memmap2 = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
