//! The four materialisers: the same corpus, written into each of Tessera's ways in.
//! [`Corpus::write_points_parquet`] and [`Corpus::write_pairs_parquet`] are the build's two
//! inputs; [`Corpus::config_toml`] is the declaration `tessera build --config` compiles;
//! [`Corpus::ingest_batch`] is `/control/ingest`'s body, in the wire shape
//! `(external_id, x, y, access, the declared scalars)`, using no engine type.
//!
//! Every writer calls [`Corpus::item`] and [`Corpus::terms`], so values agree across
//! materialisers. The parquet writers stream in bounded chunks because `n` may be 10^9.

use std::fs::File;
use std::io;
use std::ops::Range;
use std::path::Path;
use std::sync::Arc;

use arrow::array::{
    ArrayRef, BinaryBuilder, Float64Array, ListBuilder, StringArray, StringBuilder,
    TimestampMicrosecondArray, UInt32Array, UInt64Array,
};
use arrow::datatypes::{DataType, Field, Schema, TimeUnit};
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;

use crate::{Corpus, Item};

/// Rows per streamed chunk.
const CHUNK_ROWS: u64 = 1 << 16;

/// The layer and level ids the artifact fixture's closed-form kinds are materialised against.
/// `FIXTURE_LEVEL` is level 0, distinct from [`crate::artifacts::EMPTY_LEVEL`].
pub const FLAT_LAYER: u64 = 1;
pub const PARTITION_LAYER: u64 = 2;
pub const BOUNDARY_LAYER: u64 = 3;
pub const TREED_LAYER: u64 = 4;
pub const FIXTURE_LEVEL: u32 = 0;

/// The declared columns, fixed. One column per family, the join column first. Codes assign key
/// `i` of [`crate::BAY_VALUES`] to `i + 1`, code 0 being the absent sentinel.
const CONFIG_TOML: &str = r#"# The corpus's declared columns.
# Generated by tessera-corpus. The generator is the authority on values.
#
# The extent is the grid's own, because the generator works in cell coordinates: a fitted box
# would move every expected answer.
#
# The `*_artifacts`/`*_members` sources below hold the artifact fixture and are unreferenced by
# every column above; only `Corpus::write_artifact_fixtures` writes them.

[sources]
points              = "points.parquet"
pairs               = "pairs.parquet"
flat_artifacts      = "flat_artifacts.parquet"
flat_members        = "flat_members.parquet"
partition_artifacts = "partition_artifacts.parquet"
partition_members   = "partition_members.parquet"
boundary_artifacts  = "boundary_artifacts.parquet"
treed_artifacts     = "treed_artifacts.parquet"
treed_members       = "treed_members.parquet"

[defaults]
source = "points"

[[view]]
name             = "s0"
extent           = { min = 0.0, max = 65536.0 }
point_visibility = { source = "pairs", default = "public" }

[[vocabulary]]
name       = "bay"
title      = "Bay"
width      = "u8"
value_set  = "closed"
visibility = "public"
  [vocabulary.values]
  amber  = 1
  basalt = 2
  cedar  = 3
  dune   = 4
  ember  = 5
  flint  = 6
  gale   = 7

[[attribute]]
name   = "fx_key"
type   = "u64"
render = true

[[attribute]]
name   = "weight"
type   = "u32"
render = true
index  = true

[[attribute]]
name  = "seen_at"
type  = "timestamp_us"
index = true

[[attribute]]
name       = "bay"
type       = "category"
render     = true
index      = true
vocabulary = "bay"

[[attribute]]
name  = "tag"
type  = "keyword"
index = true

[[attribute]]
name     = "blurb"
type     = "text"
index    = true
analyser = "unicode"

# The partition value: single-valued over every entity, typed `u32` because the value count scales
# with `n`.
[[attribute]]
name   = "partition"
type   = "u32"
render = true
index  = true

# Enumerated, over the flat kind's membership: the layer whose membership overlaps within a level.
[[layer]]
name                      = "generator/flat"
source                    = "flat_artifacts"
views                     = ["s0"]
membership                = "enumerated"
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

  [layer.members]
  source = "flat_members"

# The partition's enumerated twin: the same relation `generator/partition-attribute` reads as a
# predicate, stored instead as a member list.
[[layer]]
name                      = "generator/partition-enumerated"
source                    = "partition_artifacts"
views                     = ["s0"]
membership                = "enumerated"
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

  [layer.members]
  source = "partition_members"

# The same partition relation, read as a predicate over the `partition` column instead of a stored
# member list. No `source`: a predicate layer's artifacts are never published, only derived.
[[layer]]
name                      = "generator/partition-attribute"
views                     = ["s0"]
membership                = { attribute = "partition" }
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

# Authored boundaries: depth-`d` Morton tiles, one artifact per authored prefix.
# `membership = "spatial"` has no member storage and no `source`. Not built yet: the engine does
# not decode a spatial predicate; this layer is a fixture for it.
[[layer]]
name                      = "generator/boundary"
views                     = ["s0"]
membership                = "spatial"
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

# The treed kind: a lineage in the artifact row's own `parent` field, `nested` because the tree is
# unbalanced. The root's membership is the whole corpus and every internal node keeps members no
# child holds.
[[layer]]
name                      = "generator/treed"
source                    = "treed_artifacts"
views                     = ["s0"]
membership                = "enumerated"
hierarchy                 = { kind = "nested" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

  [layer.members]
  source = "treed_members"
"#;

/// The declared scalar columns, in declared order.
fn scalar_fields() -> Vec<Field> {
    vec![
        Field::new("fx_key", DataType::UInt64, false),
        Field::new("weight", DataType::UInt32, true),
        Field::new(
            "seen_at",
            DataType::Timestamp(TimeUnit::Microsecond, None),
            true,
        ),
        Field::new("bay", DataType::Utf8, true),
        Field::new("tag", DataType::Utf8, true),
        Field::new("blurb", DataType::Utf8, true),
        Field::new("partition", DataType::UInt32, false),
    ]
}

fn position_fields() -> [Field; 2] {
    [
        Field::new("x", DataType::Float64, false),
        Field::new("y", DataType::Float64, false),
    ]
}

fn position_columns(items: &[Item]) -> [ArrayRef; 2] {
    let x: Float64Array = items.iter().map(|item| Some(item.x)).collect();
    let y: Float64Array = items.iter().map(|item| Some(item.y)).collect();
    [Arc::new(x), Arc::new(y)]
}

/// Write `rows` to a parquet file, [`CHUNK_ROWS`] at a time, and return how many there were.
fn write_parquet<R>(
    path: &Path,
    schema: Schema,
    rows: impl Iterator<Item = R>,
    columns: impl Fn(&[R]) -> Vec<ArrayRef>,
) -> io::Result<u64> {
    let schema = Arc::new(schema);
    let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
        .map_err(io::Error::other)?;
    let mut rows = rows.peekable();
    let mut total = 0u64;
    while rows.peek().is_some() {
        let chunk: Vec<R> = rows.by_ref().take(CHUNK_ROWS as usize).collect();
        total += chunk.len() as u64;
        let batch = RecordBatch::try_new(schema.clone(), columns(&chunk))
            .expect("every column is built from the same chunk");
        writer.write(&batch).map_err(io::Error::other)?;
    }
    writer.close().map_err(io::Error::other)?;
    Ok(total)
}

fn keys(rows: impl Iterator<Item = u64>) -> ArrayRef {
    let keys: StringArray = rows.map(|key| Some(key.to_string())).collect();
    Arc::new(keys)
}

impl Corpus {
    /// The config the build compiles for this corpus.
    pub fn config_toml(&self) -> &'static str {
        CONFIG_TOML
    }

    fn items(&self, entities: impl Iterator<Item = u64>) -> Vec<Item> {
        entities.map(|e| self.item(e)).collect()
    }

    /// One array per field of [`scalar_fields`].
    fn scalar_columns(&self, items: &[Item]) -> Vec<ArrayRef> {
        let fx_key: UInt64Array = items.iter().map(|item| Some(item.fx_key)).collect();
        let weight: UInt32Array = items.iter().map(|item| item.weight).collect();
        let seen_at: TimestampMicrosecondArray = items.iter().map(|item| item.seen_at).collect();
        let bay: StringArray = items.iter().map(|item| item.bay).collect();
        let tag: StringArray = items.iter().map(|item| item.tag.as_deref()).collect();
        let blurb: StringArray = items.iter().map(|item| item.blurb.as_deref()).collect();
        let partition: UInt32Array = items
            .iter()
            .map(|item| Some(self.partition_artifact_of(PARTITION_LAYER, item.e) as u32))
            .collect();
        vec![
            Arc::new(fx_key),
            Arc::new(weight),
            Arc::new(seen_at),
            Arc::new(bay),
            Arc::new(tag),
            Arc::new(blurb),
            Arc::new(partition),
        ]
    }

    /// Write the build's points input: `entity_id`, `x`, `y`, and every declared column. Rows
    /// `0..n`, in item order, streamed.
    pub fn write_points_parquet(&self, path: &Path) -> io::Result<()> {
        let mut fields = vec![Field::new("entity_id", DataType::UInt64, false)];
        fields.extend(position_fields());
        fields.extend(scalar_fields());
        write_parquet(path, Schema::new(fields), 0..self.n(), |entities| {
            let items = self.items(entities.iter().copied());
            let entity_id: UInt64Array = entities.iter().copied().map(Some).collect();
            let mut columns: Vec<ArrayRef> = vec![Arc::new(entity_id)];
            columns.extend(position_columns(&items));
            columns.extend(self.scalar_columns(&items));
            columns
        })?;
        Ok(())
    }

    /// Write the build's pairs input: the exploded `(entity_id, term_id)` relation for rows
    /// `0..n`, streamed.
    pub fn write_pairs_parquet(&self, path: &Path) -> io::Result<()> {
        let schema = Schema::new(vec![
            Field::new("entity_id", DataType::UInt64, false),
            Field::new("term_id", DataType::UInt32, false),
        ]);
        write_parquet(path, schema, 0..self.n(), |entities| {
            let pairs = || {
                entities
                    .iter()
                    .flat_map(|&e| self.terms(e).into_iter().map(move |term| (e, term.raw())))
            };
            let entity_id: UInt64Array = pairs().map(|(e, _)| Some(e)).collect();
            let term_id: UInt32Array = pairs().map(|(_, term)| Some(term)).collect();
            vec![Arc::new(entity_id), Arc::new(term_id)]
        })?;
        Ok(())
    }

    /// One `/control/ingest` body for items `range`, in the wire shape: `external_id`, `x`, `y`,
    /// `access` (a list of labels), then every declared scalar. `range` may start at `n`, letting
    /// a driver ingest items beyond the built prefix.
    pub fn ingest_batch(&self, range: Range<u64>) -> RecordBatch {
        let mut fields = vec![Field::new("external_id", DataType::Binary, false)];
        fields.extend(position_fields());
        fields.push(Field::new(
            "access",
            DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))),
            false,
        ));
        fields.extend(scalar_fields());

        let items = self.items(range);
        let mut external_id = BinaryBuilder::new();
        let mut access = ListBuilder::new(StringBuilder::new());
        for item in &items {
            external_id.append_value(item.e.to_le_bytes());
            for term in self.terms(item.e) {
                access.values().append_value(term.raw().to_string());
            }
            access.append(true);
        }
        let mut columns: Vec<ArrayRef> = vec![Arc::new(external_id.finish())];
        columns.extend(position_columns(&items));
        columns.push(Arc::new(access.finish()));
        columns.extend(self.scalar_columns(&items));
        RecordBatch::try_new(Arc::new(Schema::new(fields)), columns)
            .expect("every column is built from the same items")
    }

    /// One artifact roster: `key` only, one row per artifact, ascending.
    fn write_artifact_roster_parquet(
        path: &Path,
        artifacts: impl Iterator<Item = u64>,
    ) -> io::Result<()> {
        let schema = Schema::new(vec![Field::new("key", DataType::Utf8, false)]);
        write_parquet(path, schema, artifacts, |chunk| {
            vec![keys(chunk.iter().copied())]
        })?;
        Ok(())
    }

    /// The treed roster: `(key, parent)`, one row per node, `parent` null at the root.
    fn write_treed_roster_parquet(&self, path: &Path, count: u64) -> io::Result<()> {
        let schema = Schema::new(vec![
            Field::new("key", DataType::Utf8, false),
            Field::new("parent", DataType::Utf8, true),
        ]);
        write_parquet(path, schema, 0..count, |nodes| {
            let parent: StringArray = nodes
                .iter()
                .map(|&a| self.artifact_parent(a).map(|p| p.to_string()))
                .collect();
            vec![keys(nodes.iter().copied()), Arc::new(parent)]
        })?;
        Ok(())
    }

    /// One membership relation: `(key, entity)`, one row per pair. Returns the row count written.
    fn write_membership_parquet(
        path: &Path,
        pairs: impl Iterator<Item = (u64, u64)>,
    ) -> io::Result<u64> {
        let schema = Schema::new(vec![
            Field::new("key", DataType::Utf8, false),
            Field::new("entity", DataType::UInt64, false),
        ]);
        write_parquet(path, schema, pairs, |chunk| {
            let entity: UInt64Array = chunk.iter().map(|&(_, e)| Some(e)).collect();
            vec![keys(chunk.iter().map(|&(a, _)| a)), Arc::new(entity)]
        })
    }

    /// Every file the artifact fixture needs beside `points.parquet`, `pairs.parquet` and
    /// [`Corpus::config_toml`]'s declaration. Every writer walks this corpus's own size, so a
    /// smaller scale's roster and membership are freshly declared over the entities it has.
    pub fn write_artifact_fixtures(&self, dir: &Path) -> io::Result<ArtifactFixtureCounts> {
        let flat_count = self.artifacts_in(FLAT_LAYER, FIXTURE_LEVEL);
        Self::write_artifact_roster_parquet(&dir.join("flat_artifacts.parquet"), 0..flat_count)?;
        let flat_member_rows = Self::write_membership_parquet(
            &dir.join("flat_members.parquet"),
            (0..flat_count).flat_map(|a| {
                self.artifact_members(FLAT_LAYER, FIXTURE_LEVEL, a)
                    .into_iter()
                    .map(move |e| (a, e))
            }),
        )?;

        let partition_count = self.partition_count(PARTITION_LAYER);
        Self::write_artifact_roster_parquet(
            &dir.join("partition_artifacts.parquet"),
            0..partition_count,
        )?;
        let partition_member_rows = Self::write_membership_parquet(
            &dir.join("partition_members.parquet"),
            (0..self.n()).map(|e| (self.partition_artifact_of(PARTITION_LAYER, e), e)),
        )?;

        let boundary_roster = self.boundary_artifacts(BOUNDARY_LAYER, FIXTURE_LEVEL);
        Self::write_artifact_roster_parquet(
            &dir.join("boundary_artifacts.parquet"),
            boundary_roster.iter().copied(),
        )?;

        let treed_count = self.treed_count(TREED_LAYER);
        self.write_treed_roster_parquet(&dir.join("treed_artifacts.parquet"), treed_count)?;
        let treed_member_rows = Self::write_membership_parquet(
            &dir.join("treed_members.parquet"),
            (0..treed_count).flat_map(|a| {
                self.treed_members(treed_count, a)
                    .into_iter()
                    .map(move |e| (a, e))
            }),
        )?;

        Ok(ArtifactFixtureCounts {
            flat_artifacts: flat_count,
            flat_member_rows,
            treed_artifacts: treed_count,
            treed_member_rows,
            partition_artifacts: partition_count,
            partition_member_rows,
            boundary_artifacts: boundary_roster.len() as u64,
        })
    }
}

/// What [`Corpus::write_artifact_fixtures`] wrote, in closed form.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArtifactFixtureCounts {
    pub flat_artifacts: u64,
    pub flat_member_rows: u64,
    pub treed_artifacts: u64,
    pub treed_member_rows: u64,
    pub partition_artifacts: u64,
    pub partition_member_rows: u64,
    pub boundary_artifacts: u64,
}
