//! The four materialisers (spec §12.1): the same corpus, written into each of Tessera's ways in.
//!
//! One source feeding every entry point is what makes an ingested item checkable against the same
//! function as a built one. [`Corpus::write_points_parquet`] and [`Corpus::write_pairs_parquet`]
//! are the build's two inputs; [`Corpus::config_toml`] is the declaration `tessera build --config`
//! compiles; [`Corpus::ingest_batch`] is `/control/ingest`'s body, in the **wire** shape —
//! `(external_id, x, y, access, the declared scalars)` — and deliberately not any engine type.
//! The executor's `UnallocatedRow` carries resolved term ids and a view, is constructed after
//! admission, and lives in a crate §13 forbids: a corpus that could speak it would have stopped
//! being a second statement of the corpus.
//!
//! Values agree across materialisers by construction — every writer calls [`Corpus::item`] and
//! [`Corpus::terms`], never a private variant of them — and the parquet writers stream in bounded
//! chunks because `n` may be 10⁹ while this process's memory is not.

use std::fs::File;
use std::io;
use std::ops::Range;
use std::path::Path;
use std::sync::Arc;

use arrow::array::{
    ArrayRef, BinaryBuilder, Float32Builder, StringBuilder, TimestampMicrosecondBuilder,
    UInt32Builder, UInt64Builder,
};
use arrow::datatypes::{DataType, Field, Schema, TimeUnit};
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;

use crate::Corpus;

/// Rows per streamed chunk: 2¹⁶ rows keeps every builder's transient a few megabytes while giving
/// the parquet writer full row groups to accumulate.
const CHUNK_ROWS: u64 = 1 << 16;

/// The declared columns (records §2), fixed — see [`Corpus`]'s doc for why the schema is a
/// constant of the corpus rather than a parameter. One column per family, the planted join column
/// first: `fx_key` is the column the conformance fixtures already declare and the build already
/// serves (spec §8's fourth property, discharged by something that exists). Codes pin key *i* of
/// [`crate::BAY_VALUES`] to *i + 1*, code 0 being the reserved *absent* sentinel.
///
/// **The codes stay pinned rather than assigned**, which a bare `values = [...]` array would now
/// also produce in this order. [`crate::BAY_VALUES`] is indexed by code elsewhere in this crate,
/// so the pinning is the statement that ties the two together — an assignment rule that happened
/// to agree would be a coincidence a reader would have to verify.
const CONFIG_TOML: &str = r#"# The correctness-suite corpus's declared columns (correctness-suite.md §12.1).
# Generated by tessera-corpus; the generator, not this text, is the authority on values.
#
# One points file carries identity, geometry and every declared column, so the view and every
# attribute name one source; the exploded `(entity_id, term_id)` relation is the other. Both paths
# are relative to this document, which is written beside them (`configuration.md` §3).
#
# The extent is the grid's own, because the generator works in cell coordinates: its expected
# answers are stated in cells, so a fitted box would move every one of them.

[sources]
points = "points.parquet"
pairs  = "pairs.parquet"

[defaults]
source = "points"

[[view]]
name             = "s0"
extent           = { min = 0.0, max = 65536.0 }
point_visibility = { source = "pairs", default = "public" }

[[vocabulary]]
name       = "bay"
title      = "Bay"
width      = "u8"
value_set  = "closed"
visibility = "public"
  [vocabulary.values]
  amber  = 1
  basalt = 2
  cedar  = 3
  dune   = 4
  ember  = 5
  flint  = 6
  gale   = 7

[[attribute]]
name   = "fx_key"
type   = "u64"
render = true

[[attribute]]
name   = "weight"
type   = "u32"
render = true
index  = true

[[attribute]]
name  = "seen_at"
type  = "timestamp_us"
index = true

[[attribute]]
name       = "bay"
type       = "category"
render     = true
index      = true
vocabulary = "bay"

[[attribute]]
name  = "tag"
type  = "keyword"
index = true

[[attribute]]
name     = "blurb"
type     = "text"
index    = true
analyser = "unicode"
"#;

impl Corpus {
    /// The config the build compiles for this corpus — the declared columns, including the
    /// planted join column, and the one vocabulary they draw on.
    pub fn config_toml(&self) -> &'static str {
        CONFIG_TOML
    }

    /// Write the build's points input: `entity_id`, `x`, `y`, and every declared column in the
    /// form the build's scan reads it (a category as its value *key*, a timestamp as
    /// `timestamp[us]`, absence as null). Rows `0..n`, in item order, streamed.
    pub fn write_points_parquet(&self, path: &Path) -> io::Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("entity_id", DataType::UInt64, false),
            Field::new("x", DataType::Float32, false),
            Field::new("y", DataType::Float32, false),
            Field::new("fx_key", DataType::UInt64, false),
            Field::new("weight", DataType::UInt32, true),
            Field::new(
                "seen_at",
                DataType::Timestamp(TimeUnit::Microsecond, None),
                true,
            ),
            Field::new("bay", DataType::Utf8, true),
            Field::new("tag", DataType::Utf8, true),
            Field::new("blurb", DataType::Utf8, true),
        ]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut lo = 0u64;
        while lo < self.n() {
            let hi = (lo + CHUNK_ROWS).min(self.n());
            let mut entity_id = UInt64Builder::with_capacity((hi - lo) as usize);
            let mut x = Float32Builder::with_capacity((hi - lo) as usize);
            let mut y = Float32Builder::with_capacity((hi - lo) as usize);
            let mut fx_key = UInt64Builder::with_capacity((hi - lo) as usize);
            let mut weight = UInt32Builder::with_capacity((hi - lo) as usize);
            let mut seen_at = TimestampMicrosecondBuilder::with_capacity((hi - lo) as usize);
            let mut bay = StringBuilder::new();
            let mut tag = StringBuilder::new();
            let mut blurb = StringBuilder::new();
            for e in lo..hi {
                let item = self.item(e);
                entity_id.append_value(e);
                x.append_value(item.x);
                y.append_value(item.y);
                fx_key.append_value(item.fx_key);
                weight.append_option(item.weight);
                seen_at.append_option(item.seen_at);
                bay.append_option(item.bay);
                tag.append_option(item.tag.as_deref());
                blurb.append_option(item.blurb.as_deref());
            }
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(entity_id.finish()) as ArrayRef,
                    Arc::new(x.finish()),
                    Arc::new(y.finish()),
                    Arc::new(fx_key.finish()),
                    Arc::new(weight.finish()),
                    Arc::new(seen_at.finish()),
                    Arc::new(bay.finish()),
                    Arc::new(tag.finish()),
                    Arc::new(blurb.finish()),
                ],
            )
            .expect("columns built to one length from one loop");
            writer.write(&batch).map_err(io::Error::other)?;
            lo = hi;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(())
    }

    /// Write the build's pairs input: the exploded `(entity_id, term_id)` relation for rows
    /// `0..n`, in item order, streamed. Term ids are the source ids whose decimal strings become
    /// the dictionary's descriptors under `builtin:passthrough` — the same ids [`crate::Grant`]
    /// names.
    pub fn write_pairs_parquet(&self, path: &Path) -> io::Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("entity_id", DataType::UInt64, false),
            Field::new("term_id", DataType::UInt32, false),
        ]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut lo = 0u64;
        while lo < self.n() {
            let hi = (lo + CHUNK_ROWS).min(self.n());
            let mut entity_id = UInt64Builder::new();
            let mut term_id = UInt32Builder::new();
            for e in lo..hi {
                for term in self.terms(e) {
                    entity_id.append_value(e);
                    term_id.append_value(term.raw());
                }
            }
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(entity_id.finish()) as ArrayRef,
                    Arc::new(term_id.finish()),
                ],
            )
            .expect("two columns built to one length from one loop");
            writer.write(&batch).map_err(io::Error::other)?;
            lo = hi;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(())
    }

    /// One `/control/ingest` body for items `range`, in the wire shape (contracts §3.4):
    /// `external_id` (the item's 8 little-endian bytes — the workspace's existing test
    /// convention), `x`, `y`, `access` (the passthrough label: comma-joined decimal term
    /// descriptors), then every declared scalar in declared order — a category as its key, values
    /// null where the item carries none.
    ///
    /// `range` may start at `n`: the lookups are defined for every `e`, which is how a driver
    /// ingests items beyond the built prefix from the same functions (spec §12.1's "the same
    /// corpus feeds every way in").
    ///
    /// Every column emits the type the manifest declares for it
    /// (`DeclaredScalar::wire_type`), which is the only shape ingest accepts — a substitute (an
    /// `i64` for a `timestamp_us`, say) is refused as a declared-type mismatch. `seen_at` was
    /// un-ingestable when this was written, ingest having inferred types by downcast and knowing
    /// no timestamp; the decode is driven by the declaration now and the set is exhaustive.
    pub fn ingest_batch(&self, range: Range<u64>) -> RecordBatch {
        let rows = usize::try_from(range.end.saturating_sub(range.start))
            .expect("an ingest batch fits in memory by construction");
        let schema = Arc::new(Schema::new(vec![
            Field::new("external_id", DataType::Binary, false),
            Field::new("x", DataType::Float32, false),
            Field::new("y", DataType::Float32, false),
            Field::new("access", DataType::Utf8, false),
            Field::new("fx_key", DataType::UInt64, false),
            Field::new("weight", DataType::UInt32, true),
            Field::new(
                "seen_at",
                DataType::Timestamp(TimeUnit::Microsecond, None),
                true,
            ),
            Field::new("bay", DataType::Utf8, true),
            Field::new("tag", DataType::Utf8, true),
            Field::new("blurb", DataType::Utf8, true),
        ]));
        let mut external_id = BinaryBuilder::new();
        let mut x = Float32Builder::with_capacity(rows);
        let mut y = Float32Builder::with_capacity(rows);
        let mut access = StringBuilder::new();
        let mut fx_key = UInt64Builder::with_capacity(rows);
        let mut weight = UInt32Builder::with_capacity(rows);
        let mut seen_at = TimestampMicrosecondBuilder::with_capacity(rows);
        let mut bay = StringBuilder::new();
        let mut tag = StringBuilder::new();
        let mut blurb = StringBuilder::new();
        for e in range {
            let item = self.item(e);
            external_id.append_value(e.to_le_bytes());
            x.append_value(item.x);
            y.append_value(item.y);
            access.append_value(
                self.terms(e)
                    .iter()
                    .map(|t| t.raw().to_string())
                    .collect::<Vec<_>>()
                    .join(","),
            );
            fx_key.append_value(item.fx_key);
            weight.append_option(item.weight);
            seen_at.append_option(item.seen_at);
            bay.append_option(item.bay);
            tag.append_option(item.tag.as_deref());
            blurb.append_option(item.blurb.as_deref());
        }
        RecordBatch::try_new(
            schema,
            vec![
                Arc::new(external_id.finish()) as ArrayRef,
                Arc::new(x.finish()),
                Arc::new(y.finish()),
                Arc::new(access.finish()),
                Arc::new(fx_key.finish()),
                Arc::new(weight.finish()),
                Arc::new(seen_at.finish()),
                Arc::new(bay.finish()),
                Arc::new(tag.finish()),
                Arc::new(blurb.finish()),
            ],
        )
        .expect("columns built to one length from one loop")
    }
}
