//! The four materialisers (spec §12.1): the same corpus, written into each of Tessera's ways in.
//!
//! One source feeding every entry point is what makes an ingested item checkable against the same
//! function as a built one. [`Corpus::write_points_parquet`] and [`Corpus::write_pairs_parquet`]
//! are the build's two inputs; [`Corpus::config_toml`] is the declaration `tessera build --config`
//! compiles; [`Corpus::ingest_batch`] is `/control/ingest`'s body, in the **wire** shape —
//! `(external_id, x, y, access, the declared scalars)` — and deliberately not any engine type.
//! The executor's `UnallocatedRow` carries resolved term ids and a view, is constructed after
//! admission, and lives in a crate §13 forbids: a corpus that could speak it would have stopped
//! being a second statement of the corpus.
//!
//! Values agree across materialisers by construction — every writer calls [`Corpus::item`] and
//! [`Corpus::terms`], never a private variant of them — and the parquet writers stream in bounded
//! chunks because `n` may be 10⁹ while this process's memory is not.

use std::fs::File;
use std::io;
use std::ops::Range;
use std::path::Path;
use std::sync::Arc;

use arrow::array::{
    ArrayRef, BinaryBuilder, Float64Builder, StringBuilder, TimestampMicrosecondBuilder,
    UInt32Builder, UInt64Builder,
};
use arrow::datatypes::{DataType, Field, Schema, TimeUnit};
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;

use crate::Corpus;

/// Rows per streamed chunk: 2¹⁶ rows keeps every builder's transient a few megabytes while giving
/// the parquet writer full row groups to accumulate.
const CHUNK_ROWS: u64 = 1 << 16;

/// The layer and level ids the artifact fixture's closed-form arms are materialised against —
/// arbitrary but fixed, so [`Corpus::write_artifact_fixtures`] and [`CONFIG_TOML`]'s five
/// `[[layer]]` blocks agree on which arm feeds which file without a layer id column anywhere on
/// disk. `FIXTURE_LEVEL` is level 0 — not [`crate::artifacts::EMPTY_LEVEL`] — because the fixture
/// is for a build to serve, and a level with no artifacts is a Rust-level property test's case
/// ([`crate::artifacts`]'s own tests), not something the campaign's config needs a row for.
pub const FLAT_LAYER: u64 = 1;
pub const PARTITION_LAYER: u64 = 2;
pub const BOUNDARY_LAYER: u64 = 3;
pub const TREED_LAYER: u64 = 4;
pub const FIXTURE_LEVEL: u32 = 0;

/// The declared columns (records §2), fixed — see [`Corpus`]'s doc for why the schema is a
/// constant of the corpus rather than a parameter. One column per family, the planted join column
/// first: `fx_key` is the column the conformance fixtures already declare and the build already
/// serves (spec §8's fourth property, discharged by something that exists). Codes pin key *i* of
/// [`crate::BAY_VALUES`] to *i + 1*, code 0 being the reserved *absent* sentinel.
///
/// **The codes stay pinned rather than assigned**, which a bare `values = [...]` array would now
/// also produce in this order. [`crate::BAY_VALUES`] is indexed by code elsewhere in this crate,
/// so the pinning is the statement that ties the two together — an assignment rule that happened
/// to agree would be a coincidence a reader would have to verify.
const CONFIG_TOML: &str = r#"# The correctness-suite corpus's declared columns (correctness-suite.md §12.1).
# Generated by tessera-corpus; the generator, not this text, is the authority on values.
#
# One points file carries identity, geometry and every declared column, so the view and every
# attribute name one source; the exploded `(entity_id, term_id)` relation is the other. Both paths
# are relative to this document, which is written beside them (`configuration.md` §3).
#
# The extent is the grid's own, because the generator works in cell coordinates: its expected
# answers are stated in cells, so a fitted box would move every one of them.
#
# The `*_artifacts`/`*_members` sources below carry the artifact scale campaign's fixture
# (`artifact-delivery.md` §5.1) and are unreferenced by every column above — a source nothing names
# is a name in a table, not a file this build has to open, so their presence here costs an existing
# consumer nothing (`Corpus::write_points_parquet`, `write_pairs_parquet`) and only
# `Corpus::write_artifact_fixtures` writes them.

[sources]
points              = "points.parquet"
pairs               = "pairs.parquet"
flat_artifacts      = "flat_artifacts.parquet"
flat_members        = "flat_members.parquet"
partition_artifacts = "partition_artifacts.parquet"
partition_members   = "partition_members.parquet"
boundary_artifacts  = "boundary_artifacts.parquet"
treed_artifacts     = "treed_artifacts.parquet"
treed_members       = "treed_members.parquet"

[defaults]
source = "points"

[[view]]
name             = "s0"
extent           = { min = 0.0, max = 65536.0 }
point_visibility = { source = "pairs", default = "public" }

[[vocabulary]]
name       = "bay"
title      = "Bay"
width      = "u8"
value_set  = "closed"
visibility = "public"
  [vocabulary.values]
  amber  = 1
  basalt = 2
  cedar  = 3
  dune   = 4
  ember  = 5
  flint  = 6
  gale   = 7

[[attribute]]
name   = "fx_key"
type   = "u64"
render = true

[[attribute]]
name   = "weight"
type   = "u32"
render = true
index  = true

[[attribute]]
name  = "seen_at"
type  = "timestamp_us"
index = true

[[attribute]]
name       = "bay"
type       = "category"
render     = true
index      = true
vocabulary = "bay"

[[attribute]]
name  = "tag"
type  = "keyword"
index = true

[[attribute]]
name     = "blurb"
type     = "text"
index    = true
analyser = "unicode"

# The partition arm's value: single-valued over every entity (`Corpus::partition_artifact_of`),
# which is what an attribute-predicate layer's `membership = { attribute = "partition" }` reads
# below. `u32` rather than a category — the value count scales with `n` (`Corpus::partition_count`)
# and a vocabulary with millions of authored keys is not what this column is for.
[[attribute]]
name   = "partition"
type   = "u32"
render = true
index  = true

# Enumerated, over the flat arm's interval-plus-scatter membership (`artifacts.rs`) — the layer
# whose membership overlaps within a level, planted so a viewer can hold two artifacts' worth of
# one entity at once.
[[layer]]
name                      = "generator/flat"
source                    = "flat_artifacts"
views                     = ["s0"]
membership                = "enumerated"
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

  [layer.members]
  source = "flat_members"

# The partition arm's enumerated twin: the same relation `generator/partition-attribute` reads as
# a predicate, stored instead as a member list. Stage 6's equality check is that a masked count
# agrees between the two — same roster (`partition_artifacts`), same entities, different membership
# source (`configuration.md` §1).
[[layer]]
name                      = "generator/partition-enumerated"
source                    = "partition_artifacts"
views                     = ["s0"]
membership                = "enumerated"
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

  [layer.members]
  source = "partition_members"

# The same partition relation, read as a predicate over the `partition` column instead of a stored
# member list — single-valued, so the two layers must always agree on a masked count. **No
# `source`**: a predicate layer's artifacts are never published, only ever derived (the fold refuses
# publication into one — `RegistryError::NotEnumerated`), so declaring one is declaring it empty of
# anything to publish, which is exactly right here. `partition_artifacts.parquet` — the same roster
# `generator/partition-enumerated` reads — is `Corpus::write_artifact_fixtures`'s statement of which
# keys exist, for the campaign's oracle, not something this layer's declaration names.
[[layer]]
name                      = "generator/partition-attribute"
views                     = ["s0"]
membership                = { attribute = "partition" }
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

# Authored boundaries: depth-`d` Morton tiles (`boundary.rs`), one artifact per authored prefix.
# `membership = "spatial"` has no member storage and, like the attribute predicate above, no
# `source` — the engine does not yet decode a spatial predicate at all
# (`artifact-delivery.md` §5.1's "declared and unbuilt"); this layer exists so that machinery has a
# fixture to build against. `boundary_artifacts.parquet` is the oracle's roster, not this
# declaration's.
[[layer]]
name                      = "generator/boundary"
views                     = ["s0"]
membership                = "spatial"
hierarchy                 = { kind = "flat" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

# The treed arm (`hierarchy.rs`): a lineage in the artifact row's own `parent` field, `nested`
# rather than `stacked`/`tiered` because the tree is unbalanced and its own edges are the structure
# (decision 0082) — no `[[layer.levels]]`, refused if declared alongside `nested`. The root's
# membership is the whole corpus and every internal node keeps members no child holds
# (`treed_stray`), the two planted properties a covering-hierarchy generator would never produce.
[[layer]]
name                      = "generator/treed"
source                    = "treed_artifacts"
views                     = ["s0"]
membership                = "enumerated"
hierarchy                 = { kind = "nested" }
visibility                = "public"
artifact_visibility       = { default = "inherited" }
require_member_visibility = "none"

  [layer.members]
  source = "treed_members"
"#;

impl Corpus {
    /// The config the build compiles for this corpus — the declared columns, including the
    /// planted join column, and the one vocabulary they draw on.
    pub fn config_toml(&self) -> &'static str {
        CONFIG_TOML
    }

    /// Write the build's points input: `entity_id`, `x`, `y`, and every declared column in the
    /// form the build's scan reads it (a category as its value *key*, a timestamp as
    /// `timestamp[us]`, absence as null). Rows `0..n`, in item order, streamed.
    pub fn write_points_parquet(&self, path: &Path) -> io::Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("entity_id", DataType::UInt64, false),
            Field::new("x", DataType::Float64, false),
            Field::new("y", DataType::Float64, false),
            Field::new("fx_key", DataType::UInt64, false),
            Field::new("weight", DataType::UInt32, true),
            Field::new(
                "seen_at",
                DataType::Timestamp(TimeUnit::Microsecond, None),
                true,
            ),
            Field::new("bay", DataType::Utf8, true),
            Field::new("tag", DataType::Utf8, true),
            Field::new("blurb", DataType::Utf8, true),
            // The partition arm's value (`partition.rs`), single-valued and never absent — every
            // entity in `0..n` resolves to exactly one artifact. Read by
            // `membership = { attribute = "partition" }` in `CONFIG_TOML`; unreferenced by every
            // other consumer of this file, so an existing caller sees an extra column and nothing
            // else.
            Field::new("partition", DataType::UInt32, false),
        ]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut lo = 0u64;
        while lo < self.n() {
            let hi = (lo + CHUNK_ROWS).min(self.n());
            let mut entity_id = UInt64Builder::with_capacity((hi - lo) as usize);
            let mut x = Float64Builder::with_capacity((hi - lo) as usize);
            let mut y = Float64Builder::with_capacity((hi - lo) as usize);
            let mut fx_key = UInt64Builder::with_capacity((hi - lo) as usize);
            let mut weight = UInt32Builder::with_capacity((hi - lo) as usize);
            let mut seen_at = TimestampMicrosecondBuilder::with_capacity((hi - lo) as usize);
            let mut bay = StringBuilder::new();
            let mut tag = StringBuilder::new();
            let mut blurb = StringBuilder::new();
            let mut partition = UInt32Builder::with_capacity((hi - lo) as usize);
            for e in lo..hi {
                let item = self.item(e);
                entity_id.append_value(e);
                x.append_value(item.x);
                y.append_value(item.y);
                fx_key.append_value(item.fx_key);
                weight.append_option(item.weight);
                seen_at.append_option(item.seen_at);
                bay.append_option(item.bay);
                tag.append_option(item.tag.as_deref());
                blurb.append_option(item.blurb.as_deref());
                partition.append_value(self.partition_artifact_of(PARTITION_LAYER, e) as u32);
            }
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(entity_id.finish()) as ArrayRef,
                    Arc::new(x.finish()),
                    Arc::new(y.finish()),
                    Arc::new(fx_key.finish()),
                    Arc::new(weight.finish()),
                    Arc::new(seen_at.finish()),
                    Arc::new(bay.finish()),
                    Arc::new(tag.finish()),
                    Arc::new(blurb.finish()),
                    Arc::new(partition.finish()),
                ],
            )
            .expect("columns built to one length from one loop");
            writer.write(&batch).map_err(io::Error::other)?;
            lo = hi;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(())
    }

    /// Write the build's pairs input: the exploded `(entity_id, term_id)` relation for rows
    /// `0..n`, in item order, streamed. Term ids are the source ids whose decimal strings become
    /// the dictionary's descriptors under `builtin:passthrough` — the same ids [`crate::Grant`]
    /// names.
    pub fn write_pairs_parquet(&self, path: &Path) -> io::Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("entity_id", DataType::UInt64, false),
            Field::new("term_id", DataType::UInt32, false),
        ]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut lo = 0u64;
        while lo < self.n() {
            let hi = (lo + CHUNK_ROWS).min(self.n());
            let mut entity_id = UInt64Builder::new();
            let mut term_id = UInt32Builder::new();
            for e in lo..hi {
                for term in self.terms(e) {
                    entity_id.append_value(e);
                    term_id.append_value(term.raw());
                }
            }
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(entity_id.finish()) as ArrayRef,
                    Arc::new(term_id.finish()),
                ],
            )
            .expect("two columns built to one length from one loop");
            writer.write(&batch).map_err(io::Error::other)?;
            lo = hi;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(())
    }

    /// One `/control/ingest` body for items `range`, in the wire shape (contracts §3.4):
    /// `external_id` (the item's 8 little-endian bytes — the workspace's existing test
    /// convention), `x`, `y`, `access` (the passthrough label: comma-joined decimal term
    /// descriptors), then every declared scalar in declared order — a category as its key, values
    /// null where the item carries none.
    ///
    /// `range` may start at `n`: the lookups are defined for every `e`, which is how a driver
    /// ingests items beyond the built prefix from the same functions (spec §12.1's "the same
    /// corpus feeds every way in").
    ///
    /// Every column emits the type the manifest declares for it
    /// (`DeclaredScalar::wire_type`), which is the only shape ingest accepts — a substitute (an
    /// `i64` for a `timestamp_us`, say) is refused as a declared-type mismatch. `seen_at` was
    /// un-ingestable when this was written, ingest having inferred types by downcast and knowing
    /// no timestamp; the decode is driven by the declaration now and the set is exhaustive.
    pub fn ingest_batch(&self, range: Range<u64>) -> RecordBatch {
        let rows = usize::try_from(range.end.saturating_sub(range.start))
            .expect("an ingest batch fits in memory by construction");
        let schema = Arc::new(Schema::new(vec![
            Field::new("external_id", DataType::Binary, false),
            Field::new("x", DataType::Float64, false),
            Field::new("y", DataType::Float64, false),
            Field::new("access", DataType::Utf8, false),
            Field::new("fx_key", DataType::UInt64, false),
            Field::new("weight", DataType::UInt32, true),
            Field::new(
                "seen_at",
                DataType::Timestamp(TimeUnit::Microsecond, None),
                true,
            ),
            Field::new("bay", DataType::Utf8, true),
            Field::new("tag", DataType::Utf8, true),
            Field::new("blurb", DataType::Utf8, true),
        ]));
        let mut external_id = BinaryBuilder::new();
        let mut x = Float64Builder::with_capacity(rows);
        let mut y = Float64Builder::with_capacity(rows);
        let mut access = StringBuilder::new();
        let mut fx_key = UInt64Builder::with_capacity(rows);
        let mut weight = UInt32Builder::with_capacity(rows);
        let mut seen_at = TimestampMicrosecondBuilder::with_capacity(rows);
        let mut bay = StringBuilder::new();
        let mut tag = StringBuilder::new();
        let mut blurb = StringBuilder::new();
        for e in range {
            let item = self.item(e);
            external_id.append_value(e.to_le_bytes());
            x.append_value(item.x);
            y.append_value(item.y);
            access.append_value(
                self.terms(e)
                    .iter()
                    .map(|t| t.raw().to_string())
                    .collect::<Vec<_>>()
                    .join(","),
            );
            fx_key.append_value(item.fx_key);
            weight.append_option(item.weight);
            seen_at.append_option(item.seen_at);
            bay.append_option(item.bay);
            tag.append_option(item.tag.as_deref());
            blurb.append_option(item.blurb.as_deref());
        }
        RecordBatch::try_new(
            schema,
            vec![
                Arc::new(external_id.finish()) as ArrayRef,
                Arc::new(x.finish()),
                Arc::new(y.finish()),
                Arc::new(access.finish()),
                Arc::new(fx_key.finish()),
                Arc::new(weight.finish()),
                Arc::new(seen_at.finish()),
                Arc::new(bay.finish()),
                Arc::new(tag.finish()),
                Arc::new(blurb.finish()),
            ],
        )
        .expect("columns built to one length from one loop")
    }

    /// One artifact roster: `key` only, one row per artifact, ascending
    /// (`configuration.md` §1's canonical `key` field). `generator/flat`'s and
    /// `generator/partition-enumerated`'s own `source` read this shape directly; the two predicate
    /// layers (`generator/partition-attribute`, `generator/boundary`) declare no `source` at all —
    /// publication into a predicate-membership layer is refused
    /// (`RegistryError::NotEnumerated`) — so for them this file is only the campaign's oracle
    /// statement of which keys exist, never something either declaration names.
    fn write_artifact_roster_parquet(
        path: &Path,
        keys: impl Iterator<Item = u64>,
    ) -> io::Result<()> {
        let schema = Arc::new(Schema::new(vec![Field::new("key", DataType::Utf8, false)]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut key = StringBuilder::new();
        let mut buffered = 0u64;
        for k in keys {
            key.append_value(k.to_string());
            buffered += 1;
            if buffered >= CHUNK_ROWS {
                let batch = RecordBatch::try_new(schema.clone(), vec![Arc::new(key.finish())])
                    .expect("one column, built to its own length");
                writer.write(&batch).map_err(io::Error::other)?;
                buffered = 0;
            }
        }
        if buffered > 0 {
            let batch = RecordBatch::try_new(schema.clone(), vec![Arc::new(key.finish())])
                .expect("one column, built to its own length");
            writer.write(&batch).map_err(io::Error::other)?;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(())
    }

    /// The treed arm's own roster: `(key, parent)`, one row per node — `parent` null at the root,
    /// which is `generator/treed`'s `nested` lineage (`configuration.md` §1's canonical `parent`
    /// field, so no `fields` remap is needed).
    fn write_treed_roster_parquet(
        path: &Path,
        count: u64,
        parent_of: impl Fn(u64) -> Option<u64>,
    ) -> io::Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("key", DataType::Utf8, false),
            Field::new("parent", DataType::Utf8, true),
        ]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut key = StringBuilder::new();
        let mut parent = StringBuilder::new();
        let mut buffered = 0u64;
        for a in 0..count {
            key.append_value(a.to_string());
            parent.append_option(parent_of(a).map(|p| p.to_string()));
            buffered += 1;
            if buffered >= CHUNK_ROWS {
                let batch = RecordBatch::try_new(
                    schema.clone(),
                    vec![
                        Arc::new(key.finish()) as ArrayRef,
                        Arc::new(parent.finish()),
                    ],
                )
                .expect("two columns built to one length from one loop");
                writer.write(&batch).map_err(io::Error::other)?;
                buffered = 0;
            }
        }
        if buffered > 0 {
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(key.finish()) as ArrayRef,
                    Arc::new(parent.finish()),
                ],
            )
            .expect("two columns built to one length from one loop");
            writer.write(&batch).map_err(io::Error::other)?;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(())
    }

    /// One membership relation: `(key, entity)`, one row per pair — the file a `[layer.members]`
    /// reads. Streamed in [`CHUNK_ROWS`] batches over whatever `pairs` yields, so a relation the
    /// size of the corpus itself (the partition arm's, which is exhaustive) costs no more memory
    /// than the points file does.
    /// Returns the row count written, so a caller streaming the relation through does not have to
    /// walk it a second time just to report how many rows a build should see.
    fn write_membership_parquet(
        path: &Path,
        pairs: impl Iterator<Item = (u64, u64)>,
    ) -> io::Result<u64> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("key", DataType::Utf8, false),
            Field::new("entity", DataType::UInt64, false),
        ]));
        let mut writer = ArrowWriter::try_new(File::create(path)?, schema.clone(), None)
            .map_err(io::Error::other)?;
        let mut key = StringBuilder::new();
        let mut entity = UInt64Builder::new();
        let mut buffered = 0u64;
        let mut total = 0u64;
        for (k, e) in pairs {
            key.append_value(k.to_string());
            entity.append_value(e);
            buffered += 1;
            total += 1;
            if buffered >= CHUNK_ROWS {
                let batch = RecordBatch::try_new(
                    schema.clone(),
                    vec![
                        Arc::new(key.finish()) as ArrayRef,
                        Arc::new(entity.finish()),
                    ],
                )
                .expect("two columns built to one length from one loop");
                writer.write(&batch).map_err(io::Error::other)?;
                buffered = 0;
            }
        }
        if buffered > 0 {
            let batch = RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(key.finish()) as ArrayRef,
                    Arc::new(entity.finish()),
                ],
            )
            .expect("two columns built to one length from one loop");
            writer.write(&batch).map_err(io::Error::other)?;
        }
        writer.close().map_err(io::Error::other)?;
        Ok(total)
    }

    /// Every file the artifact scale campaign's fixture needs beside `points.parquet`,
    /// `pairs.parquet` and [`Corpus::config_toml`]'s declaration
    /// (`artifact-delivery.md` §5.1, §5.4) — the flat arm's roster and membership, the partition
    /// arm's roster and membership (its enumerated twin; the attribute-predicate layer reads the
    /// same roster and the `partition` points column), and the boundary arm's roster (a spatial
    /// layer stores no membership at all).
    ///
    /// **Per scale, never filtered from a larger run**: every writer below walks `0..self.n()` (or,
    /// for the boundary roster, the depth-`d` tile space, which does not depend on `n` at all) at
    /// *this* corpus's own size, which is what §5.4 requires — a smaller scale's roster and
    /// membership are freshly declared over the entities that scale has, not a filtered slice of a
    /// larger one's.
    pub fn write_artifact_fixtures(&self, dir: &Path) -> io::Result<ArtifactFixtureCounts> {
        let flat_count = self.artifacts_in(FLAT_LAYER, FIXTURE_LEVEL);
        Self::write_artifact_roster_parquet(&dir.join("flat_artifacts.parquet"), 0..flat_count)?;
        let flat_member_rows = Self::write_membership_parquet(
            &dir.join("flat_members.parquet"),
            (0..flat_count).flat_map(|a| {
                self.artifact_members(FLAT_LAYER, FIXTURE_LEVEL, a)
                    .into_iter()
                    .map(move |e| (a, e))
            }),
        )?;

        let partition_count = self.partition_count(PARTITION_LAYER);
        Self::write_artifact_roster_parquet(
            &dir.join("partition_artifacts.parquet"),
            0..partition_count,
        )?;
        let partition_member_rows = Self::write_membership_parquet(
            &dir.join("partition_members.parquet"),
            (0..self.n()).map(|e| (self.partition_artifact_of(PARTITION_LAYER, e), e)),
        )?;

        let boundary_roster = self.boundary_artifacts(BOUNDARY_LAYER, FIXTURE_LEVEL);
        Self::write_artifact_roster_parquet(
            &dir.join("boundary_artifacts.parquet"),
            boundary_roster.iter().copied(),
        )?;

        let treed_count = self.treed_count(TREED_LAYER);
        Self::write_treed_roster_parquet(&dir.join("treed_artifacts.parquet"), treed_count, |a| {
            self.artifact_parent(a)
        })?;
        let treed_member_rows = Self::write_membership_parquet(
            &dir.join("treed_members.parquet"),
            (0..treed_count).flat_map(|a| {
                self.treed_members(treed_count, a)
                    .into_iter()
                    .map(move |e| (a, e))
            }),
        )?;

        Ok(ArtifactFixtureCounts {
            flat_artifacts: flat_count,
            flat_member_rows,
            treed_artifacts: treed_count,
            treed_member_rows,
            partition_artifacts: partition_count,
            partition_member_rows,
            boundary_artifacts: boundary_roster.len() as u64,
        })
    }
}

/// What [`Corpus::write_artifact_fixtures`] wrote, in closed form — the numbers a build's own
/// report (`minted_artifacts`, member-row counts) is compared against.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArtifactFixtureCounts {
    pub flat_artifacts: u64,
    pub flat_member_rows: u64,
    pub treed_artifacts: u64,
    pub treed_member_rows: u64,
    pub partition_artifacts: u64,
    pub partition_member_rows: u64,
    pub boundary_artifacts: u64,
}
