"""The `topics/openalex` layer, proved end to end on one slice: inputs, a build, the shape it draws.

This is **not** the rung — `prepare.py` is the rung and it belongs to the vectors track, which has
not landed when this runs. This driver exists to put `openalex.py` through `tessera build` on a
slice small enough to iterate on, and it is deleted once it has done that (the brief's instruction;
the commit that carries it is named in `README-openalex.md`).

    python -m test_corpora.paperseek.smoke --out $TESSERA_LADDER/paperseek-topics-smoke

**The geometry is a hash, not a projection.** The vectors track owns the layout and its `prepare.py`
may not exist yet, so x and y here are two halves of a SplitMix64 of the work's own id. That makes
the points a uniform square of noise: it proves the build's plumbing — four levels, the parent
edges, the member rows, the computed centroid/box/hull, the licence compartment — and it proves
**nothing whatever** about whether a topic is compact in an embedding space. That measurement is
the vectors track's, on the real layout, and is what decides whether the layer stays.
"""

from __future__ import annotations

import argparse
import json
import resource
import secrets
import shutil
import time
from pathlib import Path

import numpy as np
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq

from ..common.paths import ladder, staged
from .extract import PAPERSEEK, PREFIX, VINTAGE, chunks
from .openalex import LAYER, LAYER_TOML, LICENCES, SOURCES_TOML, OpenAlex

try:
    from test_corpora.common.writer import ArtifactSet
except ImportError:  # pragma: no cover - whichever of the two is present
    from test_corpora.arxiv.writer import ArtifactSet

LIMIT = 200_000


def hash_xy(ids: np.ndarray) -> np.ndarray:
    """Two coordinates per work from SplitMix64 of its id — a square of uniform noise.

    Deterministic, so a rerun writes the same points; and stated as noise everywhere it is
    reported, so no figure taken here is read as a layout result.
    """
    z = ids.astype(np.uint64) + np.uint64(0x9E3779B97F4A7C15)
    out = np.empty((len(ids), 2), np.float64)
    for axis in range(2):
        x = z.copy()
        x ^= x >> np.uint64(30)
        x *= np.uint64(0xBF58476D1CE4E5B9)
        x ^= x >> np.uint64(27)
        x *= np.uint64(0x94D049BB133111EB)
        x ^= x >> np.uint64(31)
        out[:, axis] = (x >> np.uint64(11)).astype(np.float64) / float(1 << 53)
        z = x + np.uint64(0x9E3779B97F4A7C15)
    return out


def write_corpus_toml(out: Path) -> None:
    """The minimal declaration: one view, the licence compartment, three attributes, the layer."""
    values = "\n".join(f'  "{key}" = {i + 1}' for i, key in enumerate(LICENCES))
    (out / "corpus.toml").write_text(
        f"""# Generated by `test_corpora/paperseek/smoke.py`. The OpenAlex topic layer on one slice of
# PaperSeek, laid out by a hash of each work's id. This is the *smoke* declaration and not the
# rung's: the vectors track's `prepare.py` writes that one.

[sources]
points                = "points.parquet"
{SOURCES_TOML}
[defaults]
source          = "points"
entity_id_field = "entity_id"

# `extent = "auto"` fits the box to the coordinates as they are; the hash layout spans the unit
# square and a stated frame would put every point in one corner of the grid.
[[view]]
name             = "knn"
title            = "Scholarly map"
projection       = "none"
extent           = "auto"
source           = "points"
visibility       = "public"
point_visibility = {{ field = "licence", default = "public" }}

# **The compartment is the licence.** A work's label is its licence key; a work with no licence
# carries no label and falls through to `public`. So the principal ladder is the corpus's own
# open-access structure rather than a scheme invented for the demo: no terms at all sees the
# unlicensed majority, `cc-by` adds the largest licensed compartment, and a principal holding
# every key sees everything.

[[vocabulary]]
name       = "licence"
title      = "Licence"
width      = "u8"
value_set  = "closed"
visibility = "public"

  [vocabulary.values]
{values}

# The licence twice over, and deliberately: as the view's access label, and as a rendered
# category. An attribute is read from the column of its own name, so this is the same column —
# what a viewer is *shown* about a work they can already see, beside what decides whether they
# see it at all.
[[attribute]]
name       = "licence"
title      = "Licence"
type       = "category"
vocabulary = "licence"
render     = true

[[attribute]]
name  = "publication_year"
title = "Year"
type  = "i32"
render = true
index = true

[[attribute]]
name  = "openalex_id"
title = "OpenAlex id"
type  = "keyword"
index = true
{LAYER_TOML}"""
    )


def write_deployment(out: Path) -> None:
    """`tessera.toml`, generated: every value in it is a path or a port on this machine."""
    (out / "tessera.toml").write_text(
        """# Generated by `test_corpora/paperseek/smoke.py`. Paths and ports, and the *name* of the
# variable carrying the identity key, never the key.

[bundle]
path  = "bundle"
cache = ".tessera/cache"
wal   = ".tessera/wal.log"

[build]
schema = "corpus.toml"

[plugin]
module = "builtin:passthrough"

[identity]
env = "TESSERA_IDENTITY_KEY"

[disclosure]
token_max_lifetime = 3600

[serve]
viewer  = "127.0.0.1:8111"
session = "127.0.0.1:8112"
control = "127.0.0.1:8113"
max_k   = 5000
session_credential_env  = "TESSERA_PAPERSEEK_SESSION_CRED"
operator_credential_env = "TESSERA_PAPERSEEK_OPERATOR_CRED"

dev_cors_origins = ["http://localhost:5174", "http://127.0.0.1:5174"]
"""
    )
    (out / ".tessera").mkdir(exist_ok=True)
    env = out / ".env"
    lines = env.read_text().splitlines() if env.exists() else []
    held = {line.split("=", 1)[0] for line in lines if "=" in line}
    minted = [
        f"{var}={secrets.token_hex(16)}"
        for var in (
            "TESSERA_IDENTITY_KEY",
            "TESSERA_PAPERSEEK_SESSION_CRED",
            "TESSERA_PAPERSEEK_OPERATOR_CRED",
        )
        if var not in held
    ]
    if minted:
        env.write_text("\n".join(lines + minted) + "\n")


def prepare(oa: OpenAlex, out: Path, limit: int) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    steps: dict[str, float] = {}

    t0 = time.time()
    # The first `limit` rows of the first chunk, which are entity ids 0..limit-1 in the
    # interface's entity space (chunks in ascending numeric order, `chunk_0` first).
    ids = pq.ParquetFile(chunks()[0]).read(columns=["id"])["id"].combine_chunks()[:limit]
    steps["read"] = time.time() - t0

    t0 = time.time()
    resolved = oa.resolve(ids)
    steps["resolve"] = time.time() - t0

    number = np.asarray(
        pc.cast(pc.utf8_slice_codeunits(ids, len(PREFIX)), pa.uint64())
    )
    xy = hash_xy(number)
    entity = np.arange(len(ids), dtype=np.uint64)
    topic = np.asarray(pc.fill_null(resolved["topic"].combine_chunks(), -1))

    pq.write_table(
        pa.table(
            {
                "entity_id": pa.array(entity, pa.uint64()),
                "x": pa.array(xy[:, 0], pa.float64()),
                "y": pa.array(xy[:, 1], pa.float64()),
                "licence": resolved["licence"],
                "publication_year": resolved["publication_year"],
                # `string`, not `large_string`: the chunk's own `id` column is large and the
                # width is baked into every row of a keyword column.
                "openalex_id": pc.cast(
                    pc.utf8_slice_codeunits(ids, len(PREFIX) - 1), pa.string()
                ),
            }
        ),
        out / "points.parquet",
    )

    t0 = time.time()
    artifacts = ArtifactSet()
    # Called once here; the rung calls it once per staged slice, which is what it is written for.
    oa.write_layer(out, artifacts, topic, entity)
    artifacts.close_streams()
    artifact_rows, member_rows = artifacts.write(out, layers=[LAYER])
    steps["layer"] = time.time() - t0

    write_corpus_toml(out)
    write_deployment(out)

    licence = resolved["licence"].combine_chunks().to_pylist()
    counts: dict[str, int] = {}
    for value in licence:
        counts[value or "(none — public)"] = counts.get(value or "(none — public)", 0) + 1
    ranked = sorted(counts.items(), key=lambda kv: -kv[1])
    (out / "licence-ranks.json").write_text(
        json.dumps([{"term": t, "points": n} for t, n in ranked]) + "\n"
    )
    (out / "licence-terms.txt").write_text(
        ",".join(t for t, _ in ranked if t != "(none — public)") + "\n"
    )

    manifest = {
        "source": f"{PAPERSEEK}/{VINTAGE} chunk_0[:{limit}]",
        "rows": len(ids),
        "layout": "SplitMix64 of the work id — uniform noise, not a projection",
        "tree": oa.shape(),
        "layer": oa.artifact_shape(),
        "resolve": dict(oa.stats),
        "artifact_rows": artifact_rows,
        "member_rows": member_rows,
        "licences": ranked,
        "seconds": {k: round(v, 2) for k, v in steps.items()},
        "peak_rss_gb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20, 2),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=ladder("paperseek-topics-smoke"))
    ap.add_argument("--limit", type=int, default=LIMIT)
    ap.add_argument("--fresh", action="store_true", help="discard the output directory first")
    args = ap.parse_args()

    if args.fresh and args.out.exists():
        shutil.rmtree(args.out)
    staged(PAPERSEEK, VINTAGE)  # refuses early if the share is not mounted
    print(json.dumps(prepare(OpenAlex(), args.out, args.limit), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
