"""The MeSH layer, proved end to end on one chunk: inputs, a build, and the spread it draws.

This is not the rung. `prepare.py` is the rung and it belongs to the vectors track; this driver
exists to put `mesh.py` through `tessera build` and the viewer on a slice small enough to iterate
on, and to measure the two things the owner asked for — the module's throughput on a whole staged
chunk, and the share of the map a descriptor's members occupy, by depth.

    python -m test_corpora.medcpt.smoke --bench          # throughput over all of chunk 18
    python -m test_corpora.medcpt.smoke --out DIR        # write 200,000 articles' build inputs
    python -m test_corpora.medcpt.smoke --out DIR --spread   # after a build: the spread table

The geometry is a 2-component PCA of the MedCPT embedding rather than the rung's kNN/UMAP route.
It is real structure and not a placeholder — the same 768-dimensional vectors, projected — but it
is the *worse* of the two layouts by the arXiv rung's own measurement (`ingest-campaign.md` §4.5:
a cluster is 27–29 row runs in `pca64` against 3.5–4.1 in `knn`, and everything is "everywhere"),
so every spread figure below is a **lower bound on how well the layer draws**, not an estimate of
what the rung will show. Said here because a number measured on a PCA layout and quoted against a
UMAP one would be the wrong number twice over.
"""

from __future__ import annotations

import argparse
import json
import resource
import secrets
import shutil
import sys
import time
from pathlib import Path

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

from test_corpora.arxiv.writer import ArtifactSet
from test_corpora.medcpt.mesh import LAYER, LAYER_TOML, SOURCES_TOML, Mesh

SHARE = Path("/mnt/nas/joe/tessera/datasets/medcpt-pubmed/2026-08-27")
CHUNK = 18
LIMIT = 200_000


# ------------------------------------------------------------------------------------ the source


def read_chunk(chunk: int, limit: int | None) -> tuple[list[str], dict]:
    """The chunk's PMIDs in **embedding row order**, and the article records keyed by PMID.

    `pmids_chunk_N.json` is the row order of `embeds_chunk_N.npy`; `pubmed_chunk_N.json` is a
    pretty-printed `{pmid: {...}}` object of 1.4 GB, decoded value by value rather than through
    `json.load` so the peak is the text plus one record (the probe's approach, kept).
    """
    pmids = json.loads((SHARE / f"pmids_chunk_{chunk}.json").read_text())
    if limit is not None:
        pmids = pmids[:limit]
    wanted = set(pmids)
    records = {}
    text = (SHARE / f"pubmed_chunk_{chunk}.json").read_text()
    dec = json.JSONDecoder()
    i = text.index("{") + 1
    n = len(text)
    while True:
        while i < n and text[i] in " \t\r\n,":
            i += 1
        if text[i] == "}":
            break
        key, i = dec.raw_decode(text, i)
        while text[i] in " \t\r\n":
            i += 1
        i += 1  # the colon
        while text[i] in " \t\r\n":
            i += 1
        val, i = dec.raw_decode(text, i)
        if key in wanted:
            records[key] = val
    return [str(p) for p in pmids], records


# --------------------------------------------------------------------------------- the geometry


def pca2(path: Path, rows: int) -> np.ndarray:
    """Two principal components of the first `rows` MedCPT vectors, memory-mapped.

    The covariance is accumulated in `float64` over blocks rather than materialising a centred
    copy of the matrix — 200,000 × 768 × 4 bytes is 614 MB and there is no reason to hold two.
    """
    vectors = np.load(path, mmap_mode="r")[:rows]
    total = np.zeros(vectors.shape[1], np.float64)
    for lo in range(0, rows, 20_000):
        total += vectors[lo : lo + 20_000].sum(axis=0, dtype=np.float64)
    mean = total / rows
    cov = np.zeros((vectors.shape[1], vectors.shape[1]), np.float64)
    for lo in range(0, rows, 20_000):
        block = vectors[lo : lo + 20_000].astype(np.float64) - mean
        cov += block.T @ block
    _, components = np.linalg.eigh(cov / rows)
    axes = components[:, ::-1][:, :2]  # eigh ascends; the two largest, in order
    out = np.empty((rows, 2), np.float64)
    for lo in range(0, rows, 20_000):
        out[lo : lo + 20_000] = (vectors[lo : lo + 20_000].astype(np.float64) - mean) @ axes
    return out


# ------------------------------------------------------------------------------- the declaration


def write_corpus_toml(out: Path) -> None:
    """The minimal declaration: one view, the access column, two indexed attributes, the layer.

    Deliberately smaller than the rung's — no second view, no clustering layer, no abstracts —
    because what is being proved here is the DAG layer and everything else is scenery.
    """
    (out / "corpus.toml").write_text(
        f"""# Generated by `test_corpora/medcpt/smoke.py`. The MeSH DAG layer on one chunk of the
# MedCPT / PubMed corpus, laid out by a 2-component PCA of the embedding. This is the *smoke*
# declaration and not the rung's: `prepare.py` writes that one.

[sources]
points                = "points.parquet"
{SOURCES_TOML}
[defaults]
source          = "points"
entity_id_field = "entity_id"

# One view. `extent = "auto"` fits the box to the coordinates as they are; the PCA output spans a
# few units either side of zero and a stated frame would put the whole chunk in one corner of the
# grid, clamped rather than refused.
[[view]]
name             = "knn"
title            = "PubMed (PCA-2)"
projection       = "none"
extent           = "auto"
source           = "points"
visibility       = "public"
point_visibility = {{ field = "branches", default = "public" }}

# **The access column is `branches`** — the MeSH top-level branch letters an article's resolved
# descriptors sit under, a synthetic compartment scheme over a real column as every rung of the
# ladder uses. An article with no resolved descriptor carries the single term `unindexed` rather
# than an empty list, so `default = "public"` never fires: a point falling through to the default
# is one nothing states a policy for, and 13% of this chunk would have done so.

[[attribute]]
name  = "pmid"
title = "PMID"
type  = "keyword"
index = true

[[attribute]]
name  = "title"
type  = "text"
index = true
{LAYER_TOML}"""
    )


def write_deployment(out: Path) -> None:
    """`tessera.toml`, generated: every value in it is a path or a port on this machine. Its ports
    are its own, not the arXiv rung's — two rungs served at once are two files."""
    (out / "tessera.toml").write_text(
        """# Generated by `test_corpora/medcpt/smoke.py`. Paths and ports, and the *name* of the
# variable carrying the identity key, never the key.

[bundle]
path  = "bundle"
cache = ".tessera/cache"
wal   = ".tessera/wal.log"

[build]
schema = "corpus.toml"

[plugin]
module = "builtin:passthrough"

[identity]
env = "TESSERA_IDENTITY_KEY"

[disclosure]
token_max_lifetime = 3600

[serve]
viewer  = "127.0.0.1:8101"
session = "127.0.0.1:8102"
control = "127.0.0.1:8103"
max_k   = 5000
session_credential_env  = "TESSERA_MESH_SESSION_CRED"
operator_credential_env = "TESSERA_MESH_OPERATOR_CRED"

dev_cors_origins = ["http://localhost:5174", "http://127.0.0.1:5174"]
"""
    )
    (out / ".tessera").mkdir(exist_ok=True)
    env = out / ".env"
    lines = env.read_text().splitlines() if env.exists() else []
    held = {line.split("=", 1)[0] for line in lines if "=" in line}
    minted = [
        f"{var}={secrets.token_hex(16)}"
        for var in (
            "TESSERA_IDENTITY_KEY",
            "TESSERA_MESH_SESSION_CRED",
            "TESSERA_MESH_OPERATOR_CRED",
        )
        if var not in held
    ]
    if minted:
        env.write_text("\n".join(lines + minted) + "\n")


# ------------------------------------------------------------------------------------- the modes


def bench(mesh: Mesh) -> dict:
    """`resolve` and `closure` over all of chunk 18, timed apart from the JSON decode."""
    t0 = time.time()
    pmids, records = read_chunk(CHUNK, None)
    read_s = time.time() - t0
    m = pa.array([records.get(p, {}).get("m") or "" for p in pmids], pa.string())

    t0 = time.time()
    explicit, majors, stats = mesh.resolve(m)
    resolve_s = time.time() - t0

    t0 = time.time()
    closed = mesh.closure(explicit)
    closure_s = time.time() - t0

    t0 = time.time()
    branches = mesh.branches(explicit)
    branches_s = time.time() - t0

    rows = len(m)
    per_row = np.diff(np.asarray(closed.offsets, dtype=np.int64))
    indexed = per_row > 0
    out = dict(
        stats,
        read_seconds=round(read_s, 1),
        resolve_seconds=round(resolve_s, 2),
        closure_seconds=round(closure_s, 2),
        branches_seconds=round(branches_s, 2),
        resolve_rows_per_second=int(rows / resolve_s),
        closure_rows_per_second=int(rows / closure_s),
        explicit_rows=int(len(explicit.values)),
        closed_rows=int(len(closed.values)),
        closure_ratio=round(len(closed.values) / max(len(explicit.values), 1), 3),
        explicit_mean=round(float(len(explicit.values) / max(int(indexed.sum()), 1)), 2),
        closure_mean=round(float(per_row[indexed].mean()), 2),
        closure_median=int(np.median(per_row[indexed])),
        closure_max=int(per_row.max()),
        major_mean=round(float(len(majors.values) / max(int(indexed.sum()), 1)), 2),
        branch_terms=len({tuple(b) for b in branches.to_pylist()}),
        peak_rss_gb=round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20, 2),
    )
    return out


def prepare(mesh: Mesh, out: Path, limit: int) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    steps: dict[str, float] = {}

    t0 = time.time()
    pmids, records = read_chunk(CHUNK, limit)
    steps["read"] = time.time() - t0

    m = pa.array([records.get(p, {}).get("m") or "" for p in pmids], pa.string())
    titles = pa.array([records.get(p, {}).get("t") or "" for p in pmids], pa.string())

    t0 = time.time()
    explicit, majors, stats = mesh.resolve(m)
    closed = mesh.closure(explicit)
    branches = mesh.branches(explicit)
    steps["mesh"] = time.time() - t0

    t0 = time.time()
    xy = pca2(SHARE / f"embeds_chunk_{CHUNK}.npy", len(pmids))
    steps["pca"] = time.time() - t0

    entity = np.arange(len(pmids), dtype=np.uint64)
    pq.write_table(
        pa.table(
            {
                "entity_id": pa.array(entity, pa.uint64()),
                "x": pa.array(xy[:, 0], pa.float64()),
                "y": pa.array(xy[:, 1], pa.float64()),
                "branches": branches,
                "pmid": pa.array(pmids, pa.string()),
                "title": titles,
            }
        ),
        out / "points.parquet",
    )

    t0 = time.time()
    artifacts = ArtifactSet()
    # Called once here; the rung calls it once per staged chunk, which is what it is written for.
    mesh.write_layer(out, artifacts, closed, entity)
    artifacts.close_streams()
    artifact_rows, member_rows = artifacts.write(out, layers=[LAYER])
    steps["layer"] = time.time() - t0

    write_corpus_toml(out)
    write_deployment(out)

    # The demo's principals, in this corpus's own terms: a branch letter is the access term, so a
    # principal holding `A,B` sees the anatomy and organism articles and nothing else.
    counts: dict[str, int] = {}
    for row in branches.to_pylist():
        for term in row:
            counts[term] = counts.get(term, 0) + 1
    ranked = sorted(counts.items(), key=lambda kv: -kv[1])
    (out / "branch-ranks.json").write_text(
        json.dumps([{"term": t, "pairs": n} for t, n in ranked]) + "\n"
    )
    (out / "branch-terms.txt").write_text(",".join(t for t, _ in ranked) + "\n")

    shape = mesh.artifact_shape()
    manifest = {
        "chunk": CHUNK,
        "rows": len(pmids),
        "layout": "pca2 of the MedCPT embedding",
        "mesh_tree": mesh.shape(),
        "mesh_layer": shape,
        "resolve": {k: v for k, v in stats.items() if k != "unresolved_top"},
        "unresolved_top": stats["unresolved_top"][:10],
        "closed_rows": int(len(closed.values)),
        "closure_ratio": round(len(closed.values) / max(len(explicit.values), 1), 3),
        "artifact_rows": artifact_rows,
        "member_rows": member_rows,
        "access_terms": ranked,
        "seconds": {k: round(v, 1) for k, v in steps.items()},
        "peak_rss_gb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20, 2),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def spread(mesh: Mesh, out: Path) -> dict:
    """The share of the map an artifact's **middle 90%** of members occupies, by depth.

    The same measurement the arXiv rung's README carries for its layers, and the one that withdrew
    two taxonomies: the box between the 5th and 95th percentile of an artifact's members in x and
    in y, as a fraction of the whole map's box. A root like `humans` is everywhere by construction
    — it holds every indexed article — and the question is at what depth a descriptor starts to
    draw something, so the table is by longest-path depth (decision 0117(B)).
    """
    points = pq.read_table(out / "points.parquet", columns=["x", "y"])
    x = np.asarray(points["x"])
    y = np.asarray(points["y"])
    area = (x.max() - x.min()) * (y.max() - y.min())

    members = pq.read_table(
        out / "mesh-descriptors-members.parquet", columns=["key", "entity"]
    )
    key = members["key"].combine_chunks().dictionary_encode()
    codes = np.asarray(key.indices, dtype=np.int64)
    names = key.dictionary.to_pylist()
    entity = np.asarray(members["entity"], dtype=np.int64)

    order = np.argsort(codes, kind="stable")
    codes, entity = codes[order], entity[order]
    bounds = np.searchsorted(codes, np.arange(len(names) + 1))

    id_of = {name: i for i, name in enumerate(mesh.descriptors)}
    rows = []
    for c, name in enumerate(names):
        lo, hi = bounds[c], bounds[c + 1]
        if hi - lo < 2:
            continue
        e = entity[lo:hi]
        px = np.percentile(x[e], [5, 95])
        py = np.percentile(y[e], [5, 95])
        rows.append(
            {
                "key": name,
                "depth": int(mesh.depth[id_of[name]]),
                "members": int(hi - lo),
                "share": float((px[1] - px[0]) * (py[1] - py[0]) / area),
            }
        )

    by_depth: dict[int, list[dict]] = {}
    for r in rows:
        by_depth.setdefault(r["depth"], []).append(r)
    table = []
    for depth in sorted(by_depth):
        shares = np.array([r["share"] for r in by_depth[depth]])
        table.append(
            {
                "depth": depth,
                "artifacts": len(shares),
                "median_share": round(float(np.median(shares)), 4),
                "under_5pc": round(float((shares < 0.05).mean()), 3),
                "over_25pc": round(float((shares > 0.25).mean()), 3),
                "median_members": int(np.median([r["members"] for r in by_depth[depth]])),
            }
        )
    tightest = sorted(rows, key=lambda r: r["share"])[:10]
    widest = sorted(rows, key=lambda r: -r["share"])[:10]
    return {"by_depth": table, "tightest": tightest, "widest": widest, "artifacts": len(rows)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path)
    ap.add_argument("--limit", type=int, default=LIMIT)
    ap.add_argument("--bench", action="store_true")
    ap.add_argument("--spread", action="store_true")
    ap.add_argument("--fresh", action="store_true", help="discard the output directory first")
    args = ap.parse_args()

    mesh = Mesh()
    if args.bench:
        print(json.dumps(bench(mesh), indent=2))
        return 0
    if args.out is None:
        ap.error("--out is required unless --bench")
    if args.spread:
        print(json.dumps(spread(mesh, args.out), indent=2))
        return 0
    if args.fresh and args.out.exists():
        shutil.rmtree(args.out)
    print(json.dumps(prepare(mesh, args.out, args.limit), indent=2))
    print(
        f"\nnext:\n  cd {args.out} && tessera build\n"
        f"  ./run_demo.sh --deployment {args.out}/tessera.toml "
        f'--terms "$(cat {args.out}/branch-terms.txt)" --ranks {args.out}/branch-ranks.json '
        f"--label 'PubMed: MeSH descriptors' --prose title"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
