#!/usr/bin/env python3
"""Render the campaign table from the rungs' `measurements.json` files.

One row per rung, into a marked block of `docs/ingest-campaign.md`. The tracker is edited in place
as rungs land, so the table has to be **regenerated** rather than hand-maintained: three copies of
a conformance count had already drifted apart in this repository before they were removed, and a
campaign table hand-updated from six rungs' JSON would go the same way.

    python3 scripts/campaign_report.py                  # rewrite the block in place
    python3 scripts/campaign_report.py --check          # non-zero if the block is stale
    python3 scripts/campaign_report.py --stdout         # print it, touch nothing

    python3 scripts/campaign_report.py assemble --rung medcpt --out test_corpora/medcpt/measurements.json \
        --build stage-timings.json --bundle <bundle> --rows 35920666 \
        --serve serve-nocap.json --serve serve-6g.json --ingest ingest-10.json --ingest ingest-50.json

`assemble` is the step that turns the drivers' raw output into the one committed file, and it
lives here rather than in either driver because **the schema is one thing and the two drivers are
two**: a rung's file has a build block, zero or more serve runs and zero or more ingest cells, and
nothing that produces only one of the three can be the place its version number is decided.

**A file whose `schema_version` differs is refused, not coerced.** A rendered table is only as
true as the fields it read, and a rung measured under an older schema has fields that mean
something else — which is exactly the failure a version number exists to make loud.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CORPORA = REPO / "test_corpora"
TRACKER = REPO / "docs" / "ingest-campaign.md"

#: Bumped whenever a field in `measurements.json` changes meaning or leaves. The schema itself is
#: written down in `test_corpora/common/README.md`, with each field's unit and how it was measured.
#:
#: **2** — the ingest cycle publishes artifacts on the wire after their points (owner ruling,
#: 2026-09-03), so `content_removed` is gone (an empty base carries no roster to strip a kind
#: from), `layers` is gone (nothing is carried on an ingest batch's membership column any more) and
#: `publish` is new: what each layer's publication cost and what the roster declared that the wire
#: could not carry.
#:
#: **3** — an ingest cell carries `driver_peak_rss`, the driver process's own `VmHWM` in bytes,
#: beside the server's `fold_peak_rss`: the driver runs beside the server it loads and its growth
#: stopped rung 4's cell before the write path was measured. A cell measured before the field
#: existed carries `null`. `publish.declined` is exhaustive over the declared layers, each entry an
#: object with a `reason`, and a published layer lists the artifacts it declined over the route's
#: body cap; `--max-member-rows` is gone.
SCHEMA_VERSION = 3

BEGIN = "<!-- campaign-table: generated by scripts/campaign_report.py — do not edit by hand -->"
END = "<!-- /campaign-table -->"


def load(path: Path) -> dict:
    data = json.loads(path.read_text())
    version = data.get("schema_version")
    if version != SCHEMA_VERSION:
        raise SystemExit(
            f"{path}: schema_version is {version!r}, this script renders {SCHEMA_VERSION}. "
            f"Re-run the rung's measurement rather than reading its fields under a schema they "
            f"were not written to."
        )
    return data


def measurements() -> list[tuple[str, dict]]:
    out = []
    for path in sorted(CORPORA.glob("*/measurements.json")):
        out.append((path.parent.name, load(path)))
    return out


def si(n) -> str:
    return "—" if n is None else f"{n:,}"


def secs(n) -> str:
    if n is None:
        return "—"
    if n < 90:
        return f"{n:.1f} s"
    return f"{int(n) // 60}:{int(n) % 60:02d}"


def gb(n) -> str:
    """Decimal GB, which is the unit every figure in this tracker is already quoted in — the
    rung READMEs say 11.15 GB for a bundle of 11,150,611,895 bytes."""
    return "—" if not n else f"{n / 1e9:.2f} GB"


def ms(n) -> str:
    return "—" if n is None else (f"{n:.2f} ms" if n < 1000 else f"{n / 1000:.2f} s")


def mb(n) -> str:
    """Decimal MB. A budget-sized response is tens of these, which GB would round away."""
    return "—" if n is None else f"{n / 1e6:.1f} MB"


def marks(n) -> str:
    """A point count. A percentile over samples is a float; a mark is not."""
    return "—" if n is None else f"{n:,.0f}"


def build_row(name: str, data: dict) -> str:
    build = data.get("build") or {}
    stages = build.get("stages") or []
    top = sorted(stages, key=lambda s: -s["wall_s"])[:1]
    peak = max((s["peak_rss_kib"] for s in stages), default=None)
    return (
        f"| {name} | {si(data.get('rows'))} | {secs(build.get('wall_s'))} | "
        f"{gb(peak * 1024 if peak else None)} | {gb(build.get('bundle_bytes'))} | "
        f"{top[0]['stage'] + ' ' + secs(top[0]['wall_s']) if top else '—'} |"
    )


def serve_row(name: str, data: dict) -> list[str]:
    """One row per (cap, principal), with the shape the run's requests carried.

    A run with no `request` block did not record its shape, and every column that only means
    something under a stated shape renders `—` rather than a number a reader would compare
    against one taken at a different `k` and depth.
    """
    rows = []
    for run in data.get("serve", []):
        cap = "uncapped" if run.get("cap") is None else gb(run["cap"])
        request = run.get("request") or {}
        for rung in run.get("ladder", []):
            battery = rung.get("battery", {})

            def cell(condition: str, side: str, which: str):
                block = battery.get(condition, {}).get(side, {})
                return block.get(which, {}).get("p50")

            # Streams the server cut mid-body, over every condition, plus the first viewport's
            # own. `None` where no condition recorded the count, so a run measured before the
            # field existed reads as unknown rather than as none.
            shed = None
            if any("shed" in (battery.get(c) or {}) for c in battery):
                shed = sum((battery.get(c) or {}).get("shed", 0) for c in battery) + int(
                    bool(rung.get("first_viewport_shed"))
                )

            rows.append(
                f"| {name} | {cap} | {rung['target']:.0%} | {rung['measured']:.2%} | "
                f"{rung['terms_n']} | {si(request.get('k'))} | "
                f"{si(request.get('budget_depth'))} | "
                f"{ms(rung.get('authorise_s', 0) * 1000)} | "
                f"{ms(rung.get('first_viewport_s', 0) * 1000)} | "
                f"{marks(rung.get('first_viewport_served'))} | "
                f"{mb(rung.get('first_viewport_bytes'))} | "
                f"{marks(cell('hot', 'served', 'of_cell_p50'))} | "
                f"{mb(cell('hot', 'response_bytes', 'of_cell_p50'))} | "
                f"{ms(cell('cold', 'wall_ms', 'of_cell_p50'))} | "
                f"{ms(cell('cold_pages_warm_engine', 'wall_ms', 'of_cell_p50'))} | "
                f"{ms(cell('hot', 'wall_ms', 'of_cell_p50'))} | "
                f"{ms(cell('hot', 'stream_ms', 'of_cell_p50'))} | "
                f"{ms(cell('hot', 'server_ms', 'of_cell_p99'))} | {si(shed)} |"
            )
    return rows


def ingest_rows(name: str, data: dict) -> list[str]:
    rows = []
    for cell in data.get("ingest", []):
        equivalence = cell.get("equivalence") or {}
        verdict = (
            "—"
            if not equivalence
            else (
                "exact"
                if equivalence.get("equal")
                else "zoom-0 exact, "
                + ", ".join(
                    f"{k} {v}"
                    for k, v in sorted(equivalence.get("differences_by_surface", {}).items())
                )
                if equivalence.get("zoom0_equal")
                else f"{len(equivalence.get('differences', []))} difference(s)"
            )
        )
        blocked = cell.get("blocked")
        rows.append(
            f"| {name} | {cell['fraction']:.0%} | {cell.get('concurrency', '—')} | "
            + (
                f"**blocked**: {blocked.get('at')} |  |  |  |  |  |  |"
                if blocked
                else (
                    f"{si(cell.get('items_per_s'))} | {ms(cell.get('ack_p50'))} | "
                    f"{ms(cell.get('ack_p99'))} | {secs(cell.get('visibility_s'))} | "
                    f"{secs(cell.get('fold_s'))} | {gb(cell.get('driver_peak_rss'))} | {verdict} |"
                )
            )
        )
    return rows


def render() -> str:
    rungs = measurements()
    heading = [
        "### 1.1 The campaign table",
        "",
        "**Generated** from `test_corpora/<rung>/measurements.json` by",
        "[`../scripts/campaign_report.py`](../scripts/campaign_report.py) — every figure here is a",
        "field of a committed file, and the schema those files are on is",
        "[`../test_corpora/common/README.md`](../test_corpora/common/README.md). Do not edit this",
        "block; re-run the script.",
        "",
    ]
    if not rungs:
        return "\n".join([BEGIN, ""] + heading + ["_No rung has a `measurements.json` yet._", "", END])
    lines = [BEGIN, ""] + heading
    lines += [
        "**Build.** Wall and peak are the process's own, on local NVMe; `peak` is the highest",
        "`VmHWM` any stage reported, and `slowest stage` is from the same record.",
        "",
        "| rung | rows | build wall | peak RSS | bundle | slowest stage |",
        "|---|---|---|---|---|---|",
    ]
    lines += [build_row(name, data) for name, data in rungs]
    lines += [
        "",
        "**Serve.** One row per (cap, principal). Every request is one a client draws a whole view",
        "with: `k` is the deployment's ceiling and `depth` is how much deeper than its own zoom a",
        "request was made, so the whole extent is asked for at `depth` and a sample at zoom *z* at",
        "*z* + `depth`. `measured` is a whole-extent viewport under that principal over the same",
        "under the 100% principal — the *target* is what the greedy term composition aimed at.",
        "`first viewport` is a fresh session's first request, which carries the fragment build;",
        "`points` and `wire` beside it are what that one request served and moved, and the second",
        "pair are the median **cell**'s medians. The three latency columns are the median cell's",
        "median under each condition, end to end; `hot stream` is the same cell's whole-stream",
        "figure and `hot server p99` is its server-side p99, which stops at the sweep. `shed` is",
        "how many of that principal's requests the server cut mid-body: they carry exact counts,",
        "no latency, and are out of every figure to their left.",
        "",
        "| rung | cap | target | measured | terms | k | depth | authorise | first viewport | first points | first wire | points | wire | cold | cold pages | hot | hot stream | hot server p99 | shed |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name, data in rungs:
        lines += serve_row(name, data)
    lines += [
        "",
        "**Ingest.** *f* of the entities held back, the complement built, the hold-out ingested",
        "online. `visibility` is when a zoom-0 viewport reached the expected count after the",
        "flush, not the flush's own wall; `fold` is the server's own `compaction.last_secs`;",
        "`driver peak` is the driver process's own `VmHWM` over the whole cell, the harness's",
        "cost beside the server and not the server's (`—` where the cell predates the field).",
        "",
        "| rung | f | C | items/s | ack p50 | ack p99 | visibility | fold | driver peak | 0091 equivalence |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    ingest = []
    for name, data in rungs:
        ingest += ingest_rows(name, data)
    lines += ingest or [
        "| — | — | — | — | — | — | — | — | — | _no rung has an ingest cell; see each rung's `notes`_ |"
    ]
    lines += ["", END]
    return "\n".join(lines)


def ingest_cell(cell: dict) -> dict:
    """One `ingest_cycle.py` output on the schema's §3 shape.

    A function rather than an inline literal in [`assemble`] because a rung measured before a
    schema change is re-collated from its driver output by the same mapping, and two copies of it
    would be two schemas.
    """
    return {
        "fraction": cell["fraction"],
        "concurrency": cell["concurrency"],
        "seed": cell.get("seed"),
        "base_rows": cell.get("base_rows"),
        "holdout_rows": cell.get("holdout_rows"),
        "blocked": cell.get("blocked"),
        "base_build": {
            k: v for k, v in (cell.get("build") or {}).items() if k != "stages"
        },
        "base_build_stages": (cell.get("build") or {}).get("stages"),
        # What publication cost: per layer, the artifacts, members and parent edges that
        # landed, and artifacts/s and members/s. A declined layer is named here with its
        # reason, so a layer census difference below is attributable.
        "publish": cell.get("publish"),
        "items_per_s": (cell.get("ingest") or {}).get("items_per_s"),
        "accepted": (cell.get("ingest") or {}).get("accepted"),
        "ack_p50": ((cell.get("ingest") or {}).get("ack_ms") or {}).get("p50"),
        "ack_p99": ((cell.get("ingest") or {}).get("ack_ms") or {}).get("p99"),
        "statuses": (cell.get("ingest") or {}).get("statuses"),
        # The byte cap the bodies were kept under and what the driver did to keep them there
        # (`test_corpora/common/README.md` §3): a cell whose 422s are all single-row bodies over
        # the cap is a different finding from one whose driver stalled.
        "max_body_bytes": (cell.get("ingest") or {}).get("max_body_bytes"),
        "bodies_split": (cell.get("ingest") or {}).get("bodies_split"),
        "largest_body_bytes": (cell.get("ingest") or {}).get("largest_body_bytes"),
        "bodies_over_cap": (cell.get("ingest") or {}).get("bodies_over_cap"),
        "flush_s": (cell.get("flush") or {}).get("publish_s"),
        "visibility_s": (cell.get("flush") or {}).get("visibility_s"),
        "fold_s": (cell.get("fold") or {}).get("fold_s"),
        "fold_peak_rss": (cell.get("fold") or {}).get("fold_peak_rss_bytes"),
        "driver_peak_rss": cell.get("driver_peak_rss"),
        "equivalence": {
            k: v
            for k, v in (cell.get("equivalence") or {}).items()
            if k not in ("folded", "all_in")
        },
        "write_cycle": cell.get("write_cycle"),
    }


def assemble(args) -> int:
    """Collate a rung's driver outputs into one `measurements.json` on the schema.

    Every field is copied rather than recomputed: a figure that this script derived would be a
    second definition of a number the driver already measured, and the two would drift.
    """
    build: dict = {}
    if args.build:
        stages = json.loads(Path(args.build).read_text())
        build["stages"] = stages
        build["wall_s"] = round(sum(s["wall_s"] for s in stages), 2)
        build["peak_rss_kib"] = max((s["peak_rss_kib"] for s in stages), default=None)
    if args.bundle:
        bundle = Path(args.bundle)
        build["bundle_bytes"] = sum(p.stat().st_size for p in bundle.rglob("*") if p.is_file())
    # `peak_anon` / `peak_file` come from a sampler run beside the build, not from `VmHWM`, which
    # cannot separate the two. Absent unless one was run — never guessed from the total.
    if args.rss_report:
        build["rss"] = json.loads(Path(args.rss_report).read_text())

    serve = []
    for path in args.serve or []:
        run = json.loads(Path(path).read_text())
        serve.append(run)

    ingest = [ingest_cell(json.loads(Path(path).read_text())) for path in args.ingest or []]

    out = {
        "schema_version": SCHEMA_VERSION,
        "rung": args.rung,
        "rows": args.rows,
        "binary_commit": args.commit,
        "built_at": args.built_at,
        "host": args.host,
        "build": build,
        "serve": serve,
        "ingest": ingest,
        "notes": args.note or [],
    }
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"wrote {args.out}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="command")
    asm = sub.add_parser("assemble", help="collate one rung's driver outputs onto the schema")
    asm.add_argument("--rung", required=True)
    asm.add_argument("--out", required=True)
    asm.add_argument("--rows", type=int, default=None)
    asm.add_argument("--build", default=None, help="the build's --stage-timings-json")
    asm.add_argument("--bundle", default=None)
    asm.add_argument("--rss-report", default=None)
    asm.add_argument("--serve", action="append")
    asm.add_argument("--ingest", action="append")
    asm.add_argument("--commit", default=None)
    asm.add_argument("--built-at", default=None)
    asm.add_argument("--host", default=None)
    asm.add_argument("--note", action="append")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--tracker", default=str(TRACKER))
    args = ap.parse_args(argv)
    if args.command == "assemble":
        return assemble(args)

    block = render()
    if args.stdout:
        print(block)
        return 0

    tracker = Path(args.tracker)
    text = tracker.read_text()
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END) :]
        new = head + block + tail
    else:
        # First render: the block goes at the end of §1, before the next heading.
        marker = "\n## 2. "
        at = text.index(marker) if marker in text else len(text)
        new = text[:at] + "\n" + block + "\n" + text[at:]

    if args.check:
        if new != text:
            print(f"{tracker}: the campaign table is stale — run scripts/campaign_report.py")
            return 1
        return 0
    if new != text:
        tracker.write_text(new)
        print(f"rewrote the campaign table in {tracker}")
    else:
        print("the campaign table is already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
