#!/usr/bin/env python3
"""check-corpus-integrity.py — make changes to the invariants and the leak register visible.

Rescoping an invariant or adding a leak-register row is a few words inside a thousand-line
document. In review it is invisible: the diff shows a paragraph changed, and the reader has to
already know which paragraph mattered. That is not a hypothetical — an audit found one invariant
number silently covering two different properties, only one of which was implemented, and a
reviewer grepping the number concluded both were.

This script generates `docs/design/inventory.md` from the corpus: every invariant with its
statement, every leak-register row with its concern and status, each document's revision, and the
count of specified-but-unimplemented markers. The file is committed. Changing an invariant
therefore produces a one-line diff in a small file that cannot be read past.

    python3 scripts/check-corpus-integrity.py            # regenerate, then check it is committed
    python3 scripts/check-corpus-integrity.py --write    # regenerate without checking

Exit 1 if regenerating changes the committed file — i.e. the corpus moved and the inventory did
not. The fix is to commit the regenerated inventory in the same change, which is the point.

The inventory is also a machine-readable list the conformance suite can assert its coverage
against. Today nothing checks that the invariant→test mapping is complete.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESIGN = ROOT / "docs" / "design"
INVENTORY = DESIGN / "inventory.md"

# **I7 — Sampling happens after masking, never before.** …
INVARIANT = re.compile(r"^\*\*(I\d+[a-z]?)\s*[—–-]\s*(.+?)\*\*", re.M)
# | C4 | concern | what it reveals | severity | mitigation | status |
# `\b[^|]*` not `\s*`: rows C17-C19 carry a revision tag between the number and the pipe
# (`| C17 *(r21)* |`). An earlier version anchored on `\s*` and silently dropped all three —
# including the row a rewrite had just edited. A checker that under-reports is worse than none.
LEAK_ROW = re.compile(r"^\|\s*(C\d+)\b[^|]*\|([^|]*)\|[^|]*\|([^|]*)\|[^|]*\|([^|]*)\|", re.M)
REVISION = re.compile(r"^\*\*Status:\*\*\s*(.+?)$", re.M)
UNBUILT = re.compile(r"⊘")


def first_sentence(s: str) -> str:
    s = re.sub(r"\s+", " ", s).strip().rstrip(".")
    s = re.sub(r"[*`]", "", s)
    return s


def read(name: str) -> str:
    p = DESIGN / name
    return p.read_text() if p.exists() else ""


def build() -> str:
    arch = read("architecture.md")

    invs = [(i, first_sentence(t)) for i, t in INVARIANT.findall(arch)]
    leaks = [
        (c, first_sentence(concern), first_sentence(sev), first_sentence(status))
        for c, concern, sev, status in LEAK_ROW.findall(arch)
    ]

    docs = []
    for p in sorted(DESIGN.glob("*.md")):
        if p.name in ("inventory.md", "DIVERGENCE-REGISTER.md", "README.md"):
            continue
        t = p.read_text()
        m = REVISION.search(t)
        raw = first_sentence(m.group(1)) if m else ""
        rev = re.search(r"\br(\d+)\b|revision\s+(\d+)", raw, re.I)
        if "Provisional" in raw:
            status = "Provisional — under review"
        elif rev:
            status = f"Normative — r{rev.group(1) or rev.group(2)}"
        else:
            status = raw.split(" — ")[0][:40] or "—"
        docs.append((p.name, status, len(UNBUILT.findall(t))))

    out = [
        "# Corpus inventory",
        "",
        "**Generated by `scripts/check-corpus-integrity.py`. Do not edit by hand.**",
        "",
        "This exists so that a change to an invariant or to the leak register is a one-line diff in",
        "a small file rather than a few words buried in a thousand-line document. If a line here",
        "changes, something load-bearing changed, and the commit that changes it should say why.",
        "",
        f"## Invariants ({len({i.rstrip('abc') for i, _ in invs})} numbered)",
        "",
        "I13 states two distinct properties with different scopes, different implementations and",
        "different evidence. They are lettered so that confirming one cannot be read as covering",
        "the other.",
        "",
        "| | |",
        "|---|---|",
    ]
    out += [f"| **{i}** | {t} |" for i, t in invs]
    out += [
        "",
        f"## Leak register ({len(leaks)} rows)",
        "",
        "Exhaustive by construction: a disclosure not in this table is a bug, not an omission.",
        "",
        "| | Concern | Severity | Status |",
        "|---|---|---|---|",
    ]
    out += [f"| **{c}** | {concern} | {sev} | {status} |" for c, concern, sev, status in leaks]
    out += [
        "",
        "## Documents",
        "",
        "`⊘` counts claims marked specified-but-not-implemented (decision 0013).",
        "",
        "| Document | Status | ⊘ |",
        "|---|---|---|",
    ]
    out += [f"| `{n}` | {s} | {u or ''} |" for n, s, u in docs]
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="regenerate without checking git state")
    args = ap.parse_args()

    content = build()
    previous = INVENTORY.read_text() if INVENTORY.exists() else None
    INVENTORY.write_text(content)

    n_stated = content.count("| **I")
    n_numbered = len({m.rstrip("abc") for m in re.findall(r"\| \*\*(I\d+[a-z]?)\*\*", content)})
    n_leak = content.count("| **C")
    print(f"inventory: {n_numbered} numbered invariants ({n_stated} lettered statements), "
          f"{n_leak} leak-register rows")

    if args.write:
        return 0
    if previous is None:
        print("ERROR: inventory did not exist; it has been generated — commit it", file=sys.stderr)
        return 1
    if previous != content:
        print("\nERROR: the corpus changed and docs/design/inventory.md did not.", file=sys.stderr)
        print("Regenerated it. Review the diff — if an invariant or a leak-register row moved,", file=sys.stderr)
        print("say why in the commit message — then commit it alongside your change.", file=sys.stderr)
        subprocess.run(["git", "--no-pager", "diff", "--", str(INVENTORY)], cwd=ROOT)
        return 1
    print("inventory is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
