"""The concurrency sweep: 1 / 8 / 32 / 128 sessions at mixed breadths, panning.

**The envelope is the deliverable, not a pass/fail count** (the campaign's plan, §8). What this
records per concurrency is where latency starts to degrade and what binds first — the compute
gate's queue, the server's resident set, or the machine's cores. Every session is its own principal
with its own `M_auth`: masks are not shared, which is the scenario the owner set, and it is what
makes 128 sessions 128 bitmaps rather than one.

**Broad principals are capped at 8 concurrent**, the row-projection cache's sizing. Above that the
mix is median and narrow, which is also the realistic shape: a deployment has a few analysts who
can see most of the corpus and many who cannot.

**The load itself is generated by
[`artifact_campaign_load`](../../crates/tessera-bench/src/bin/artifact_campaign_load.rs), not by
this file**, and the reason is recorded because it invalidated a first set of numbers: a single
Python process with a thread per session sat at 1.4 of 12 cores at eight sessions — the GIL — while
the server sat at the same, and the plateau it reported was the harness's rather than the engine's.
This script spawns the server, chooses the mix, runs the Rust load arm once per concurrency level
and collects its report beside the gate's own gauges.

Panning is a walk of the viewport ladder rather than one repeated request, so the caches are
exercised the way a moving map exercises them instead of being answered from one warm entry.

Run: `python3 concurrency.py --work DIR --levels 1 8 32 128 --seconds 45`
"""

from __future__ import annotations

import argparse
import json
import random
import subprocess
import time
from pathlib import Path

import campaign as C


def pan_route(rng: random.Random) -> list[C.Viewport]:
    """A session's pan route: eight boxes at a mix of zooms, jittered across the grid.

    Kept here because `fold_under_load.py` and `ingest_during_serving.py` still drive their session
    counts from Python, where at 32 sessions reading undecoded bodies the harness is not the bound.
    The Rust load arm draws the identical route by the same rule.
    """
    ladder = C.viewports()
    route = []
    for _ in range(8):
        vp = rng.choice(ladder)
        side = C.GRID * (vp.fraction ** 0.5)
        x = rng.uniform(0.0, max(0.0, C.GRID - side))
        y = rng.uniform(0.0, max(0.0, C.GRID - side))
        route.append(C.Viewport(vp.name, [x, y, x + side, y + side], vp.zoom, vp.fraction))
    return route


def mix_for(level: int, broad_cap: int) -> list[str]:
    """The breadth mix at one concurrency: broad up to the cap, then median, then narrow.

    At 32 that is 2 broad / 6 median / 24 narrow — the plan's own example — and the same rule
    scales it to 1, 8 and 128.
    """
    broad = min(broad_cap, max(1, level // 16))
    median = min(level - broad, max(1, level // 5))
    narrow = level - broad - median
    return ["0.9375"] * broad + ["0.25"] * median + ["0.031"] * max(0, narrow)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", required=True, type=Path)
    ap.add_argument("--levels", nargs="*", type=int, default=[1, 8, 32, 128])
    ap.add_argument("--seconds", type=float, default=45.0)
    ap.add_argument("--layer", default=C.LAYER_PARTITION_ATTR)
    ap.add_argument("--broad-cap", type=int, default=8)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    work: Path = args.work
    load_bin = C.REPO_ROOT / "target" / "release" / "artifact_campaign_load"

    ports = (C.free_port(), C.free_port(), C.free_port())
    C.write_deployment(work, ports)
    server = C.Server(work, *ports)
    server.spawn()
    results = []
    try:
        for level in args.levels:
            mix = mix_for(level, args.broad_cap)
            counts: dict[str, int] = {}
            for breadth in mix:
                counts[breadth] = counts.get(breadth, 0) + 1
            argv = [
                str(load_bin),
                "--viewer", server.viewer_base,
                "--session", server.session_base,
                "--session-credential", C.SESSION_CREDENTIAL,
                "--fixture-json", str(work / "fixture" / "fixture.json"),
                "--layer", args.layer,
                "--seconds", str(args.seconds),
                "--server-pid", str(server.proc.pid),
            ]
            for breadth, count in counts.items():
                argv += ["--mix", f"{breadth}={count}"]
            print(f"concurrency {level}: mix {counts}")
            proc = subprocess.run(argv, capture_output=True, text=True)
            if proc.returncode != 0:
                raise SystemExit(f"load arm exited {proc.returncode}:\n{proc.stderr[-3000:]}")
            row = json.loads(proc.stdout)
            row["concurrency"] = level
            status = server.status()
            row["compute_gate"] = status.get("compute")
            row["row_projection_cache"] = status.get("row_projection_cache")
            row["fragment_cache"] = status.get("fragment_cache")
            row["sessions_stats"] = status.get("sessions")
            results.append(row)
            print(
                f"  {row['requests']} req in {row['seconds']:.1f}s — "
                f"{row['throughput_rps']:.2f} rps, p50 {row['p50_ms']:.1f} ms, "
                f"p99 {row['p99_ms']:.1f} ms, RSS {row['server_peak_rss_bytes'] / 1024**2:.0f} MB, "
                f"{row['server_cores_busy']:.2f} of 12 cores, "
                f"{row['bytes_per_second'] / 1e6:.0f} MB/s, {row['errors']} error(s)"
            )
            # Let the box settle between levels, so one level's tail is not the next one's start.
            time.sleep(5)
    finally:
        server.stop()

    out = args.out or (work / "concurrency.json")
    out.write_text(json.dumps(results, indent=2))
    print(f"\n-> {out}")


if __name__ == "__main__":
    main()
